package com.zypg.cms.work.model.am;


import com.zypg.cms.work.model.am.common.CoursewareAM;
import com.zypg.cms.work.model.viewobject.book.query.CmsBookQVOImpl;
import com.zypg.cms.work.model.viewobject.book.query.CmsBookVOImpl;
import com.zypg.cms.work.model.viewobject.book.query.CmsBookVORowImpl;
import com.zypg.cms.work.model.viewobject.common.CmsDocCategoryRelTVOImpl;
import com.zypg.cms.work.model.viewobject.common.CmsDocCategoryRelTVORowImpl;
import com.zypg.cms.work.model.viewobject.common.CmsDocTVOImpl;
import com.zypg.cms.work.model.viewobject.common.CmsDocTVORowImpl;
import com.zypg.cms.work.model.viewobject.common.CmsDocUcmRelTVOImpl;
import com.zypg.cms.work.model.viewobject.courseware.CmsCoursewareTVOImpl;
import com.zypg.cms.work.model.viewobject.courseware.CmsCoursewareTVORowImpl;
import com.zypg.cms.work.model.viewobject.courseware.query.CmsCoursewareQVOImpl;
import com.zypg.cms.work.model.viewobject.courseware.query.CmsCoursewareQueryVOImpl;
import com.zypg.cms.work.model.viewobject.courseware.query.CmsCoursewareVOImpl;
import com.zypg.cms.work.model.viewobject.relation.CmsDocRelTVOImpl;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 24 15:04:27 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CoursewareAMImpl extends ApplicationModuleImpl implements CoursewareAM {
    /**
     * This is the default constructor (do not remove).
     */
    public CoursewareAMImpl() {
    }

    /**
     * Container's getter for CmsCoursewareVO.
     * @return CmsCoursewareVO
     */
    public CmsCoursewareVOImpl getCmsCoursewareVO() {
        return (CmsCoursewareVOImpl)findViewObject("CmsCoursewareVO");
    }

    public Number preEditCourseware(String mode, Number docId, String compCode) {
        this.getDBTransaction().getSession().getUserData().put("compCode", compCode);
        Number result = null;
        CmsCoursewareTVOImpl cmsCoursewareTVO = this.getCmsCoursewareTVO();
        if ("CREATE".equals(mode)) {
            CmsDocTVOImpl docVO = this.getCmsDocTVO();
            CmsDocTVORowImpl docNewRow = (CmsDocTVORowImpl)docVO.createRow();
            docNewRow.setStatus("TO_GATHER_COURSEWARE");
            docNewRow.setLibCode("COURSEWARE");
            docNewRow.setLibTypeCode("END_PROD_LIB");
            docNewRow.setCompCode(compCode);
            docVO.insertRow(docNewRow);
            CmsCoursewareTVORowImpl coursewareNewRow = (CmsCoursewareTVORowImpl)cmsCoursewareTVO.createRow();
            coursewareNewRow.setDocId(docNewRow.getDocId());
            //判断是否是从图书库进入
            if (docId != null) {
                CmsBookVOImpl bookVO = this.getCmsBookVO();
                bookVO.setbvDocId(docId);
                bookVO.executeQuery();
                CmsBookVORowImpl bookRow = (CmsBookVORowImpl)bookVO.first();
                if (bookRow != null) {
                    coursewareNewRow.setTeachingMaterialName(bookRow.getBookName());
                    coursewareNewRow.setTeachingMaterialIsbn(bookRow.getIsbn());
                    coursewareNewRow.setTeachingMaterialAuthor(bookRow.getAuthor());
                    coursewareNewRow.setCoursewareName(bookRow.getBookName());
                    coursewareNewRow.setTeachingMaterialSeriesName(bookRow.getSeries());
                    coursewareNewRow.setTeachingMaterialType(bookRow.getCategoryName());
                    CmsDocCategoryRelTVOImpl docCategoryRelVO = this.getCmsDocCategoryRelTVO();
                    Row[] relRows = docCategoryRelVO.getFilteredRows("DocId", docId);
                    if (relRows.length > 0) {
                        CmsDocCategoryRelTVORowImpl docCategoryRelRow = (CmsDocCategoryRelTVORowImpl)relRows[0];
                        System.out.println("docCategoryRelRow.getCategoryId():" + docCategoryRelRow.getCategoryId());
                        preDocCategroupRel(docNewRow.getDocId(), docCategoryRelRow.getCategoryId());
                    } else {
                        preDocCategroupRel(docNewRow.getDocId(), new Number(-1));
                    }
                }
            }
            coursewareNewRow.setUploadTime(new oracle.jbo.domain.Date(new java.sql.Timestamp(new java.util.Date().getTime())));
            cmsCoursewareTVO.insertRow(coursewareNewRow);
            result = docNewRow.getDocId();
        } else {
            cmsCoursewareTVO.setbvDocId(docId);
            cmsCoursewareTVO.executeQuery();
            Row row = cmsCoursewareTVO.first();
            if (row != null) {
                row.setAttribute("LastUpdateDate", new Date());
                cmsCoursewareTVO.setCurrentRow(row);
            }
            result = docId;
        }
        return result;
    }

    public void preDocCategroupRel(Number docId, Number categoryId) {
        CmsDocCategoryRelTVOImpl docCategoryRelVO = this.getCmsDocCategoryRelTVO();
        docCategoryRelVO.setbvDocId(docId);
        docCategoryRelVO.executeQuery();
        Row row = docCategoryRelVO.first();
        if (row == null) {
            CmsDocCategoryRelTVORowImpl docCategoryRelNewRow =
                (CmsDocCategoryRelTVORowImpl)docCategoryRelVO.createRow();
            docCategoryRelNewRow.setDocId(docId);
            docCategoryRelNewRow.setCategoryGroupType("BY_CATEGORY");
            docCategoryRelNewRow.setCategoryId(categoryId);
            docCategoryRelVO.insertRow(docCategoryRelNewRow);
        } else {
            CmsDocCategoryRelTVORowImpl docCategoryRelNewRow = (CmsDocCategoryRelTVORowImpl)row;
            docCategoryRelNewRow.setCategoryId(categoryId);
        }
    }

    public void initCoursewareInfo4View(Number docId) {
        CmsCoursewareTVOImpl coursewareVO = this.getCmsCoursewareTVO4View();
        coursewareVO.setbvDocId(docId);
        coursewareVO.executeQuery();
        CmsDocUcmRelTVOImpl durTVO = this.getCmsDocUcmRelTVO4FileList();
        durTVO.setbvDocId(docId);
        durTVO.executeQuery();
        Row row = coursewareVO.first();
        if (row != null) {
            coursewareVO.setCurrentRow(row);
        }
    }

    public long initOnlineReadInfo(Number docId) {
        CmsDocUcmRelTVOImpl onlineReadVO = this.getCmsDocUcmRelTVO4OnlineRead();
        onlineReadVO.setbvDocId(docId);
        onlineReadVO.executeQuery();
        onlineReadVO.setRangeSize(-1);
        return onlineReadVO.getEstimatedRowCount();
    }

    /**
     * 初始化高级查询面板
     */
    public void initComplexSearch4Courseware() {
        CmsCoursewareQVOImpl vo = this.getCmsCoursewareQVO();
        vo.executeQuery();
        vo.setCurrentRow(vo.first());
    }

    /**
     * Container's getter for CmsCoursewareTVO.
     * @return CmsCoursewareTVO
     */
    public CmsCoursewareTVOImpl getCmsCoursewareTVO() {
        return (CmsCoursewareTVOImpl)findViewObject("CmsCoursewareTVO");
    }


    /**
     * Container's getter for CmsDocTVO.
     * @return CmsDocTVO
     */
    public CmsDocTVOImpl getCmsDocTVO() {
        return (CmsDocTVOImpl)findViewObject("CmsDocTVO");
    }

    /**
     * Container's getter for CmsDocCategoryRelTVO.
     * @return CmsDocCategoryRelTVO
     */
    public CmsDocCategoryRelTVOImpl getCmsDocCategoryRelTVO() {
        return (CmsDocCategoryRelTVOImpl)findViewObject("CmsDocCategoryRelTVO");
    }

    /**
     * Container's getter for CmsBookVO.
     * @return CmsBookVO
     */
    public CmsBookVOImpl getCmsBookVO() {
        return (CmsBookVOImpl)findViewObject("CmsBookVO");
    }

    /**
     * Container's getter for CmsCoursewareTVO4View.
     * @return CmsCoursewareTVO4View
     */
    public CmsCoursewareTVOImpl getCmsCoursewareTVO4View() {
        return (CmsCoursewareTVOImpl)findViewObject("CmsCoursewareTVO4View");
    }

    /**
     * Container's getter for CmsDocRelTVO.
     * @return CmsDocRelTVO
     */
    public CmsDocRelTVOImpl getCmsDocRelTVO() {
        return (CmsDocRelTVOImpl)findViewObject("CmsDocRelTVO");
    }

    /**
     * Container's getter for CmsDocUcmRelTVO4FileList.
     * @return CmsDocUcmRelTVO4FileList
     */
    public CmsDocUcmRelTVOImpl getCmsDocUcmRelTVO4FileList() {
        return (CmsDocUcmRelTVOImpl)findViewObject("CmsDocUcmRelTVO4FileList");
    }

    /**
     * Container's getter for CmsDocUcmRelTVO4OnlineRead.
     * @return CmsDocUcmRelTVO4OnlineRead
     */
    public CmsDocUcmRelTVOImpl getCmsDocUcmRelTVO4OnlineRead() {
        return (CmsDocUcmRelTVOImpl)findViewObject("CmsDocUcmRelTVO4OnlineRead");
    }

    /**
     * Container's getter for CmsCoursewareQueryVO.
     * @return CmsCoursewareQueryVO
     */
    public CmsCoursewareQueryVOImpl getCmsCoursewareQueryVO() {
        return (CmsCoursewareQueryVOImpl)findViewObject("CmsCoursewareQueryVO");
    }

    /**
     * Container's getter for CmsCoursewareQVO.
     * @return CmsCoursewareQVO
     */
    public CmsCoursewareQVOImpl getCmsCoursewareQVO() {
        return (CmsCoursewareQVOImpl)findViewObject("CmsCoursewareQVO");
    }
}
