package com.zypg.cms.work.model.am;


import com.honythink.applicationframework.hadf.CustomApplicationModuleImpl;

import com.zypg.cms.work.model.viewobject.audio.query.CmsAudioVOImpl;
import com.zypg.cms.work.model.viewobject.audio.query.CmsAudioVORowImpl;
import com.zypg.cms.work.model.viewobject.book.CmsJbInfoTVOImpl;
import com.zypg.cms.work.model.viewobject.book.CmsXcInfoTVOImpl;
import com.zypg.cms.work.model.viewobject.book.query.CmsBookQVOImpl;
import com.zypg.cms.work.model.viewobject.common.CmsDocCategoryRelTVOImpl;
import com.zypg.cms.work.model.viewobject.common.CmsDocCategoryRelTVORowImpl;
import com.zypg.cms.work.model.viewobject.common.CmsDocTVOImpl;
import com.zypg.cms.work.model.viewobject.common.CmsDocTVORowImpl;
import com.zypg.cms.work.model.viewobject.common.CmsDocUcmRelTVOImpl;
import com.zypg.cms.work.model.viewobject.common.CmsDocUcmRelTVORowImpl;
import com.zypg.cms.work.model.viewobject.elecprod.CmsElecProdEditVOImpl;
import com.zypg.cms.work.model.viewobject.elecprod.CmsElecProdEditVORowImpl;
import com.zypg.cms.work.model.viewobject.elecprod.CmsElecProdTVOImpl;
import com.zypg.cms.work.model.viewobject.elecprod.CmsElecProdTVORowImpl;
import com.zypg.cms.work.model.viewobject.elecprod.query.CmsElecProdQVOImpl;
import com.zypg.cms.work.model.viewobject.elecprod.query.CmsElecProdQueryVOImpl;
import com.zypg.cms.work.model.viewobject.elecprod.query.CmsElecProdVOImpl;
import com.zypg.cms.work.model.viewobject.video.query.CmsVideoVOImpl;
import com.zypg.cms.work.model.viewobject.video.query.CmsVideoVORowImpl;

import java.sql.SQLException;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 18 13:24:12 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ElecProdAMImpl extends CustomApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ElecProdAMImpl() {
    }


    /****************************************电子音像库相关**************************************************************/
    public Number preEditElecProd(String mode, Number docId, String compCode, String compName) {
        Number result = null;
        CmsElecProdTVOImpl cmsElecProdTVO = this.getCmsElecProdTVO();
        if ("CREATE".equals(mode)) {
            CmsDocTVOImpl docVO = this.getCmsDocTVO();
            CmsDocTVORowImpl docNewRow = (CmsDocTVORowImpl)docVO.createRow();
            docNewRow.setStatus("TO_GATHER_ELEC_PROD");
            docNewRow.setLibCode("ELEC_PROD");
            docNewRow.setLibTypeCode("END_PROD_LIB");
            docNewRow.setCompCode(compCode);
            docVO.insertRow(docNewRow);
            CmsElecProdTVORowImpl elecProdNewRow = (CmsElecProdTVORowImpl)cmsElecProdTVO.createRow();
            elecProdNewRow.setDocId(docNewRow.getDocId());
            elecProdNewRow.setPublishingHouse(compName);
            cmsElecProdTVO.insertRow(elecProdNewRow);

            preDocCategroupRel(mode, docNewRow.getDocId());
            result = elecProdNewRow.getDocId();
        } else {
            result = docId;
            cmsElecProdTVO.setbvDocId(docId);
            cmsElecProdTVO.executeQuery();
            Row row = cmsElecProdTVO.first();
            if (row != null) {
                row.setAttribute("LastUpdateDate", new Date());
                cmsElecProdTVO.setCurrentRow(row);
            }
            preDocCategroupRel(mode, docId);
        }
        return result;
    }

    public void preDocCategroupRel(String mode, Number docId) {
        CmsDocCategoryRelTVOImpl docCategoryRelVO = this.getCmsDocCategoryRelTVO();
        if ("CREATE".equals(mode)) {
            CmsDocCategoryRelTVORowImpl docCategoryRelNewRow =
                (CmsDocCategoryRelTVORowImpl)docCategoryRelVO.createRow();
            docCategoryRelNewRow.setDocId(docId);
            docCategoryRelNewRow.setCategoryGroupType("BY_CATEGORY");
            docCategoryRelNewRow.setCategoryId(new Number(-1));
            docCategoryRelVO.insertRow(docCategoryRelNewRow);
        } else {
            docCategoryRelVO.setbvDocId(docId);
            docCategoryRelVO.executeQuery();
            Row row = docCategoryRelVO.first();
            if (row != null) {
                docCategoryRelVO.setCurrentRow(row);
            }
        }
    }

    public void initElecProdEditVO() {
        CmsElecProdEditVOImpl vo = this.getCmsElecProdEditVO();
        vo.executeQuery();
        Row row = vo.first();
        if (row != null) {
            vo.setCurrentRow(row);
        }
    }

    public String initInfo4View(Number docId) {
        String url = null;
        CmsElecProdTVOImpl vo = this.getCmsElecProdTVO4View();
        vo.setbvDocId(docId);
        vo.executeQuery();
        CmsDocUcmRelTVOImpl durTVO = this.getCmsDocUcmRelTVO4FileList();
        durTVO.setbvDocId(docId);
        durTVO.executeQuery();
        CmsDocUcmRelTVORowImpl row = (CmsDocUcmRelTVORowImpl)durTVO.first();
        if (null != row) {
            oracle.jbo.domain.Number firstDocId = row.getRefDocId();
            if ("AUDIO".equals(row.getDocType())) {
                CmsAudioVOImpl audioVO = this.getCmsAudioVO4View();
                audioVO.setbvDocId(firstDocId);
                audioVO.executeQuery();
                CmsAudioVORowImpl audioRow = (CmsAudioVORowImpl)audioVO.first();
                if (audioRow != null) {
                    url = audioRow.getPreviewUrl();
                }
            } else if ("VIDEO".equals(row.getDocType())) {
                CmsVideoVOImpl videoVO = this.getCmsVideoVO4View();
                videoVO.setbvDocId(firstDocId);
                CmsVideoVORowImpl videoRow = (CmsVideoVORowImpl)videoVO.first();
                if (videoRow != null) {
                    url = videoRow.getPreviewUrl();
                }
            }
        }
        return url;
    }

    public void batchEditElecProd(String docIds) {
        String[] docId = docIds.split(",");
        CmsElecProdTVOImpl elecProdVO = this.getCmsElecProdTVO();
        CmsElecProdEditVOImpl editVO = this.getCmsElecProdEditVO();
        CmsElecProdEditVORowImpl editRow = (CmsElecProdEditVORowImpl)editVO.getCurrentRow();
        for (String id : docId) {
            try {
                elecProdVO.setbvDocId(new Number(id));
            } catch (SQLException e) {
                e.printStackTrace();
            }
            elecProdVO.executeQuery();
            Row row = elecProdVO.first();
            if (row != null) {
                CmsElecProdTVORowImpl elecProdRow = (CmsElecProdTVORowImpl)row;
                for (String attr : editRow.getAttributeNames()) {
                    if (editRow.getAttribute(attr) != null) {
                        if ("Keyword".equals(attr)) {
                            String oldKeyword = elecProdRow.getKeyword();
                            String newKeyword = null;
                            if (oldKeyword == null) {
                                newKeyword = editRow.getAttribute(attr) + "";
                            } else {
                                newKeyword = oldKeyword + "," + editRow.getAttribute(attr);
                            }
                            elecProdRow.setAttribute(attr, newKeyword);
                        } else {
                            elecProdRow.setAttribute(attr, editRow.getAttribute(attr));
                        }
                    }
                }
                elecProdRow.setLastUpdatedBy(this.getCustomDBTransaction().getUserId());
                elecProdRow.setLastUpdateDate(new Date());
                try {
                    if (editRow.getCategoryId() != null) {
                        updateCategoryRel(editRow.getCategoryId(), new Number(id));
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    public void updateCategoryRel(Number categoryId, Number docId) {
        CmsDocCategoryRelTVOImpl docCategoryRelVO = this.getCmsDocCategoryRelTVO();
        docCategoryRelVO.setbvDocId(docId);
        docCategoryRelVO.executeQuery();
        Row row = docCategoryRelVO.first();
        if (row != null) {
            CmsDocCategoryRelTVORowImpl docCategoryRelNewRow = (CmsDocCategoryRelTVORowImpl)row;
            docCategoryRelNewRow.setCategoryId(categoryId);
        }
    }

    public Number preScriptElecprod(Number docId) {
        CmsElecProdTVOImpl elecprodVO = this.getCmsElecProdTVO();
        elecprodVO.setbvDocId(docId);
        elecprodVO.executeQuery();
        Row r = elecprodVO.first();
        if (r != null) {
            CmsElecProdTVORowImpl row = (CmsElecProdTVORowImpl)r;
            elecprodVO.setCurrentRow(row);
        }
        return null;
    }

    /**
     * 初始化高级查询面板
     */
    public void initComplexSearch4ElecProd() {
        CmsElecProdQVOImpl vo = this.getCmsElecProdQVO();
        vo.executeQuery();
        vo.setCurrentRow(vo.first());
    }

    /**
     * Container's getter for CmsElecProdTVO.
     * @return CmsElecProdTVO
     */
    public CmsElecProdTVOImpl getCmsElecProdTVO() {
        return (CmsElecProdTVOImpl)findViewObject("CmsElecProdTVO");
    }

    /**
     * Container's getter for CmsDocTVO.
     * @return CmsDocTVO
     */
    public CmsDocTVOImpl getCmsDocTVO() {
        return (CmsDocTVOImpl)findViewObject("CmsDocTVO");
    }

    /**
     * Container's getter for CmsElecProdVO.
     * @return CmsElecProdVO
     */
    public CmsElecProdVOImpl getCmsElecProdVO() {
        return (CmsElecProdVOImpl)findViewObject("CmsElecProdVO");
    }

    /**
     * Container's getter for CmsDocCategoryRelTVO.
     * @return CmsDocCategoryRelTVO
     */
    public CmsDocCategoryRelTVOImpl getCmsDocCategoryRelTVO() {
        return (CmsDocCategoryRelTVOImpl)findViewObject("CmsDocCategoryRelTVO");
    }

    /**
     * Container's getter for CmsElecProdEditVO.
     * @return CmsElecProdEditVO
     */
    public CmsElecProdEditVOImpl getCmsElecProdEditVO() {
        return (CmsElecProdEditVOImpl)findViewObject("CmsElecProdEditVO");
    }

    /**
     * Container's getter for CmsElecProdTVO4View.
     * @return CmsElecProdTVO4View
     */
    public CmsElecProdTVOImpl getCmsElecProdTVO4View() {
        return (CmsElecProdTVOImpl)findViewObject("CmsElecProdTVO4View");
    }


    /**
     * Container's getter for CmsDocUcmRelTVO4FileList.
     * @return CmsDocUcmRelTVO4FileList
     */
    public CmsDocUcmRelTVOImpl getCmsDocUcmRelTVO4FileList() {
        return (CmsDocUcmRelTVOImpl)findViewObject("CmsDocUcmRelTVO4FileList");
    }

    /**
     * Container's getter for CmsAudioVO4View.
     * @return CmsAudioVO4View
     */
    public CmsAudioVOImpl getCmsAudioVO4View() {
        return (CmsAudioVOImpl)findViewObject("CmsAudioVO4View");
    }

    /**
     * Container's getter for CmsVideoVO4View.
     * @return CmsVideoVO4View
     */
    public CmsVideoVOImpl getCmsVideoVO4View() {
        return (CmsVideoVOImpl)findViewObject("CmsVideoVO4View");
    }

    /**
     * Container's getter for CmsJbInfoTVO4View.
     * @return CmsJbInfoTVO4View
     */
    public CmsJbInfoTVOImpl getCmsJbInfoTVO4View() {
        return (CmsJbInfoTVOImpl)findViewObject("CmsJbInfoTVO4View");
    }

    /**
     * Container's getter for CmsElecProd2JbInfoVL1.
     * @return CmsElecProd2JbInfoVL1
     */
    public ViewLinkImpl getCmsElecProd2JbInfoVL1() {
        return (ViewLinkImpl)findViewLink("CmsElecProd2JbInfoVL1");
    }

    /**
     * Container's getter for CmsXcInfoTVO4View.
     * @return CmsXcInfoTVO4View
     */
    public CmsXcInfoTVOImpl getCmsXcInfoTVO4View() {
        return (CmsXcInfoTVOImpl)findViewObject("CmsXcInfoTVO4View");
    }

    /**
     * Container's getter for CmsElecProd2XcInfoVL1.
     * @return CmsElecProd2XcInfoVL1
     */
    public ViewLinkImpl getCmsElecProd2XcInfoVL1() {
        return (ViewLinkImpl)findViewLink("CmsElecProd2XcInfoVL1");
    }

    /**
     * Container's getter for CmsElecProdQueryVO.
     * @return CmsElecProdQueryVO
     */
    public CmsElecProdQueryVOImpl getCmsElecProdQueryVO() {
        return (CmsElecProdQueryVOImpl)findViewObject("CmsElecProdQueryVO");
    }

    /**
     * Container's getter for CmsElecProdQVO.
     * @return CmsElecProdQVO
     */
    public CmsElecProdQVOImpl getCmsElecProdQVO() {
        return (CmsElecProdQVOImpl)findViewObject("CmsElecProdQVO");
    }
}
