package com.zypg.cms.work.model.viewobject.common.query;

import java.math.BigDecimal;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 06 10:13:27 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CmsCategoryQueryVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CategoryId {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getCategoryId();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setCategoryId((Number)value);
            }
        }
        ,
        CategoryName {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getCategoryName();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setCategoryName((String)value);
            }
        }
        ,
        ParentNodeType {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getParentNodeType();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setParentNodeType((String)value);
            }
        }
        ,
        Seq {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getSeq();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setSeq((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        ParentNodeId {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getParentNodeId();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setParentNodeId((Number)value);
            }
        }
        ,
        CompCode {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getCompCode();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setCompCode((String)value);
            }
        }
        ,
        LibCode {
            public Object get(CmsCategoryQueryVORowImpl obj) {
                return obj.getLibCode();
            }

            public void put(CmsCategoryQueryVORowImpl obj, Object value) {
                obj.setLibCode((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CmsCategoryQueryVORowImpl object);

        public abstract void put(CmsCategoryQueryVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int CATEGORYNAME = AttributesEnum.CategoryName.index();
    public static final int PARENTNODETYPE = AttributesEnum.ParentNodeType.index();
    public static final int SEQ = AttributesEnum.Seq.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int PARENTNODEID = AttributesEnum.ParentNodeId.index();
    public static final int COMPCODE = AttributesEnum.CompCode.index();
    public static final int LIBCODE = AttributesEnum.LibCode.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CmsCategoryQueryVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryId.
     * @return the CategoryId
     */
    public Number getCategoryId() {
        return (Number) getAttributeInternal(CATEGORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryId.
     * @param value value to set the  CategoryId
     */
    public void setCategoryId(Number value) {
        setAttributeInternal(CATEGORYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryName.
     * @return the CategoryName
     */
    public String getCategoryName() {
        return (String) getAttributeInternal(CATEGORYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryName.
     * @param value value to set the  CategoryName
     */
    public void setCategoryName(String value) {
        setAttributeInternal(CATEGORYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ParentNodeType.
     * @return the ParentNodeType
     */
    public String getParentNodeType() {
        return (String) getAttributeInternal(PARENTNODETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ParentNodeType.
     * @param value value to set the  ParentNodeType
     */
    public void setParentNodeType(String value) {
        setAttributeInternal(PARENTNODETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Seq.
     * @return the Seq
     */
    public Number getSeq() {
        return (Number) getAttributeInternal(SEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Seq.
     * @param value value to set the  Seq
     */
    public void setSeq(Number value) {
        setAttributeInternal(SEQ, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute1.
     * @param value value to set the  Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute2.
     * @param value value to set the  Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute3.
     * @param value value to set the  Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute4.
     * @param value value to set the  Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute5.
     * @param value value to set the  Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute6.
     * @param value value to set the  Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute7.
     * @param value value to set the  Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute8.
     * @param value value to set the  Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute9.
     * @param value value to set the  Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute10.
     * @param value value to set the  Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute11.
     * @param value value to set the  Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute12.
     * @param value value to set the  Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute13.
     * @param value value to set the  Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute14.
     * @param value value to set the  Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute15.
     * @param value value to set the  Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ParentNodeId.
     * @return the ParentNodeId
     */
    public Number getParentNodeId() {
        return (Number) getAttributeInternal(PARENTNODEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ParentNodeId.
     * @param value value to set the  ParentNodeId
     */
    public void setParentNodeId(Number value) {
        setAttributeInternal(PARENTNODEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompCode.
     * @return the CompCode
     */
    public String getCompCode() {
        return (String) getAttributeInternal(COMPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompCode.
     * @param value value to set the  CompCode
     */
    public void setCompCode(String value) {
        setAttributeInternal(COMPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LibCode.
     * @return the LibCode
     */
    public String getLibCode() {
        return (String) getAttributeInternal(LIBCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LibCode.
     * @param value value to set the  LibCode
     */
    public void setLibCode(String value) {
        setAttributeInternal(LIBCODE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
