package com.zypg.cms.work.model.viewobject.common.query;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 10 16:53:26 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CmsUserCompVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CompCode {
            public Object get(CmsUserCompVORowImpl obj) {
                return obj.getCompCode();
            }

            public void put(CmsUserCompVORowImpl obj, Object value) {
                obj.setCompCode((String)value);
            }
        }
        ,
        CompName {
            public Object get(CmsUserCompVORowImpl obj) {
                return obj.getCompName();
            }

            public void put(CmsUserCompVORowImpl obj, Object value) {
                obj.setCompName((String)value);
            }
        }
        ,
        UserId {
            public Object get(CmsUserCompVORowImpl obj) {
                return obj.getUserId();
            }

            public void put(CmsUserCompVORowImpl obj, Object value) {
                obj.setUserId((BigDecimal)value);
            }
        }
        ,
        Seq {
            public Object get(CmsUserCompVORowImpl obj) {
                return obj.getSeq();
            }

            public void put(CmsUserCompVORowImpl obj, Object value) {
                obj.setSeq((BigDecimal)value);
            }
        }
        ,
        GroupFlag {
            public Object get(CmsUserCompVORowImpl obj) {
                return obj.getGroupFlag();
            }

            public void put(CmsUserCompVORowImpl obj, Object value) {
                obj.setGroupFlag((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CmsUserCompVORowImpl object);

        public abstract void put(CmsUserCompVORowImpl object, Object value);

        public int index() {
            return CmsUserCompVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return CmsUserCompVORowImpl.AttributesEnum.firstIndex() + CmsUserCompVORowImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = CmsUserCompVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COMPCODE = AttributesEnum.CompCode.index();
    public static final int COMPNAME = AttributesEnum.CompName.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int SEQ = AttributesEnum.Seq.index();
    public static final int GROUPFLAG = AttributesEnum.GroupFlag.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CmsUserCompVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CompCode.
     * @return the CompCode
     */
    public String getCompCode() {
        return (String) getAttributeInternal(COMPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompCode.
     * @param value value to set the  CompCode
     */
    public void setCompCode(String value) {
        setAttributeInternal(COMPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompName.
     * @return the CompName
     */
    public String getCompName() {
        return (String) getAttributeInternal(COMPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompName.
     * @param value value to set the  CompName
     */
    public void setCompName(String value) {
        setAttributeInternal(COMPNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UserId.
     * @return the UserId
     */
    public BigDecimal getUserId() {
        return (BigDecimal) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UserId.
     * @param value value to set the  UserId
     */
    public void setUserId(BigDecimal value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Seq.
     * @return the Seq
     */
    public BigDecimal getSeq() {
        return (BigDecimal) getAttributeInternal(SEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Seq.
     * @param value value to set the  Seq
     */
    public void setSeq(BigDecimal value) {
        setAttributeInternal(SEQ, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GroupFlag.
     * @return the GroupFlag
     */
    public String getGroupFlag() {
        return (String) getAttributeInternal(GROUPFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GroupFlag.
     * @param value value to set the  GroupFlag
     */
    public void setGroupFlag(String value) {
        setAttributeInternal(GROUPFLAG, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
