package com.zypg.cms.work.model.viewobject.theme.origin;

import java.math.BigDecimal;

import java.sql.Timestamp;

import java.util.Hashtable;

import java.util.List;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 09 22:28:55 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CmsWorksEntryOriginVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        EntryId {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getEntryId();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setEntryId((Number)value);
            }
        }
        ,
        DocId {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getDocId();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setDocId((Number)value);
            }
        }
        ,
        Title {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getTitle();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setTitle((String)value);
            }
        }
        ,
        Subtitle {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getSubtitle();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setSubtitle((String)value);
            }
        }
        ,
        EnglishTitle {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getEnglishTitle();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setEnglishTitle((String)value);
            }
        }
        ,
        EnglishSubtitle {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getEnglishSubtitle();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setEnglishSubtitle((String)value);
            }
        }
        ,
        Source {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getSource();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setSource((String)value);
            }
        }
        ,
        Author {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getAuthor();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setAuthor((String)value);
            }
        }
        ,
        Translator {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getTranslator();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setTranslator((String)value);
            }
        }
        ,
        Lang {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getLang();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setLang((String)value);
            }
        }
        ,
        WordCount {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getWordCount();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setWordCount((Number)value);
            }
        }
        ,
        WritingTime {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getWritingTime();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setWritingTime((Date)value);
            }
        }
        ,
        StoreTime {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getStoreTime();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setStoreTime((Date)value);
            }
        }
        ,
        Keyword {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getKeyword();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setKeyword((String)value);
            }
        }
        ,
        AbstarctDesc {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getAbstarctDesc();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setAbstarctDesc((String)value);
            }
        }
        ,
        Checked {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getChecked();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setChecked((Boolean)value);
            }
        }
        ,
        CategoryId {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getCategoryId();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setCategoryId((Number)value);
            }
        }
        ,
        CategoryName {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getCategoryName();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setCategoryName((String)value);
            }
        }
        ,
        Status {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        CompCode {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getCompCode();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setCompCode((String)value);
            }
        }
        ,
        CompName {
            public Object get(CmsWorksEntryOriginVORowImpl obj) {
                return obj.getCompName();
            }

            public void put(CmsWorksEntryOriginVORowImpl obj, Object value) {
                obj.setCompName((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CmsWorksEntryOriginVORowImpl object);

        public abstract void put(CmsWorksEntryOriginVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ENTRYID = AttributesEnum.EntryId.index();
    public static final int DOCID = AttributesEnum.DocId.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int SUBTITLE = AttributesEnum.Subtitle.index();
    public static final int ENGLISHTITLE = AttributesEnum.EnglishTitle.index();
    public static final int ENGLISHSUBTITLE = AttributesEnum.EnglishSubtitle.index();
    public static final int SOURCE = AttributesEnum.Source.index();
    public static final int AUTHOR = AttributesEnum.Author.index();
    public static final int TRANSLATOR = AttributesEnum.Translator.index();
    public static final int LANG = AttributesEnum.Lang.index();
    public static final int WORDCOUNT = AttributesEnum.WordCount.index();
    public static final int WRITINGTIME = AttributesEnum.WritingTime.index();
    public static final int STORETIME = AttributesEnum.StoreTime.index();
    public static final int KEYWORD = AttributesEnum.Keyword.index();
    public static final int ABSTARCTDESC = AttributesEnum.AbstarctDesc.index();
    public static final int CHECKED = AttributesEnum.Checked.index();
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int CATEGORYNAME = AttributesEnum.CategoryName.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int COMPCODE = AttributesEnum.CompCode.index();
    public static final int COMPNAME = AttributesEnum.CompName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CmsWorksEntryOriginVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute EntryId.
     * @return the EntryId
     */
    public Number getEntryId() {
        return (Number)getAttributeInternal(ENTRYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EntryId.
     * @param value value to set the  EntryId
     */
    public void setEntryId(Number value) {
        setAttributeInternal(ENTRYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocId.
     * @return the DocId
     */
    public Number getDocId() {
        return (Number)getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocId.
     * @param value value to set the  DocId
     */
    public void setDocId(Number value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Title.
     * @return the Title
     */
    public String getTitle() {
        return (String)getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Title.
     * @param value value to set the  Title
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Subtitle.
     * @return the Subtitle
     */
    public String getSubtitle() {
        return (String)getAttributeInternal(SUBTITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Subtitle.
     * @param value value to set the  Subtitle
     */
    public void setSubtitle(String value) {
        setAttributeInternal(SUBTITLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EnglishTitle.
     * @return the EnglishTitle
     */
    public String getEnglishTitle() {
        return (String)getAttributeInternal(ENGLISHTITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EnglishTitle.
     * @param value value to set the  EnglishTitle
     */
    public void setEnglishTitle(String value) {
        setAttributeInternal(ENGLISHTITLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EnglishSubtitle.
     * @return the EnglishSubtitle
     */
    public String getEnglishSubtitle() {
        return (String)getAttributeInternal(ENGLISHSUBTITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EnglishSubtitle.
     * @param value value to set the  EnglishSubtitle
     */
    public void setEnglishSubtitle(String value) {
        setAttributeInternal(ENGLISHSUBTITLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Source.
     * @return the Source
     */
    public String getSource() {
        return (String)getAttributeInternal(SOURCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Source.
     * @param value value to set the  Source
     */
    public void setSource(String value) {
        setAttributeInternal(SOURCE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Author.
     * @return the Author
     */
    public String getAuthor() {
        return (String)getAttributeInternal(AUTHOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Author.
     * @param value value to set the  Author
     */
    public void setAuthor(String value) {
        setAttributeInternal(AUTHOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Translator.
     * @return the Translator
     */
    public String getTranslator() {
        return (String)getAttributeInternal(TRANSLATOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Translator.
     * @param value value to set the  Translator
     */
    public void setTranslator(String value) {
        setAttributeInternal(TRANSLATOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Lang.
     * @return the Lang
     */
    public String getLang() {
        return (String)getAttributeInternal(LANG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Lang.
     * @param value value to set the  Lang
     */
    public void setLang(String value) {
        setAttributeInternal(LANG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WordCount.
     * @return the WordCount
     */
    public Number getWordCount() {
        return (Number)getAttributeInternal(WORDCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WordCount.
     * @param value value to set the  WordCount
     */
    public void setWordCount(Number value) {
        setAttributeInternal(WORDCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WritingTime.
     * @return the WritingTime
     */
    public Date getWritingTime() {
        return (Date)getAttributeInternal(WRITINGTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WritingTime.
     * @param value value to set the  WritingTime
     */
    public void setWritingTime(Date value) {
        setAttributeInternal(WRITINGTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StoreTime.
     * @return the StoreTime
     */
    public Date getStoreTime() {
        return (Date)getAttributeInternal(STORETIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StoreTime.
     * @param value value to set the  StoreTime
     */
    public void setStoreTime(Date value) {
        setAttributeInternal(STORETIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Keyword.
     * @return the Keyword
     */
    public String getKeyword() {
        return (String)getAttributeInternal(KEYWORD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Keyword.
     * @param value value to set the  Keyword
     */
    public void setKeyword(String value) {
        setAttributeInternal(KEYWORD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AbstarctDesc.
     * @return the AbstarctDesc
     */
    public String getAbstarctDesc() {
        return (String)getAttributeInternal(ABSTARCTDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AbstarctDesc.
     * @param value value to set the  AbstarctDesc
     */
    public void setAbstarctDesc(String value) {
        setAttributeInternal(ABSTARCTDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Checked.
     * @return the Checked
     */
    public Boolean getChecked() {
        Boolean result = null;
        Hashtable map = this.getDBTransaction().getSession().getUserData();
        String prefix = "ORIGIN";
        String selectAllFlag = (String)map.get(prefix + "_selectAllFlag");
        String key = prefix + "_" + this.getDocId();
        List<String> currSelectedList = (List<String>)map.get(prefix + "_currSelected");
        if ("O".equals(selectAllFlag)) {
            if (currSelectedList.contains(key)) {
                result = true;
            } else {
                result = false;
            }
        } else {
            if ("Y".equals(selectAllFlag)) {
                result = true;
            } else if ("N".equals(selectAllFlag)) {
                result = false;
            }
        }
        try {
            this.setChecked(result);
        } catch (Exception e) {
            //            e.printStackTrace();
        }
        return (Boolean)getAttributeInternal(CHECKED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Checked.
     * @param value value to set the  Checked
     */
    public void setChecked(Boolean value) {
        setAttributeInternal(CHECKED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryId.
     * @return the CategoryId
     */
    public Number getCategoryId() {
        return (Number)getAttributeInternal(CATEGORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryId.
     * @param value value to set the  CategoryId
     */
    public void setCategoryId(Number value) {
        setAttributeInternal(CATEGORYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryName.
     * @return the CategoryName
     */
    public String getCategoryName() {
        return (String)getAttributeInternal(CATEGORYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryName.
     * @param value value to set the  CategoryName
     */
    public void setCategoryName(String value) {
        setAttributeInternal(CATEGORYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Status.
     * @param value value to set the  Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompCode.
     * @return the CompCode
     */
    public String getCompCode() {
        return (String) getAttributeInternal(COMPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompCode.
     * @param value value to set the  CompCode
     */
    public void setCompCode(String value) {
        setAttributeInternal(COMPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompName.
     * @return the CompName
     */
    public String getCompName() {
        return (String) getAttributeInternal(COMPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompName.
     * @param value value to set the  CompName
     */
    public void setCompName(String value) {
        setAttributeInternal(COMPNAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
