package com.zypg.cms.work.model.am.client;

import com.zypg.cms.work.model.am.common.ActivityAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 25 11:23:28 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ActivityAMClient extends ApplicationModuleImpl implements ActivityAM {
    /**
     * This is the default constructor (do not remove).
     */
    public ActivityAMClient() {
    }


    public void preEidtActivity(String mode, oracle.jbo.domain.Number docId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"preEidtActivity",new String [] {"java.lang.String","oracle.jbo.domain.Number"},new Object[] {mode, docId});
        return;
    }


    public void initActivityEditVO() {
        Object _ret = this.riInvokeExportedMethod(this,"initActivityEditVO",null,null);
        return;
    }
}
