package com.zypg.cms.work.model.am.client;


import com.zypg.cms.work.model.am.common.AttachAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 23 17:36:48 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AttachAMClient extends ApplicationModuleImpl implements AttachAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AttachAMClient() {
    }

    public void preMgmtAttach(Number docId, String libCode, String compCode) {
        Object _ret =
            this.riInvokeExportedMethod(this, "preMgmtAttach", new String[] { "oracle.jbo.domain.Number", "java.lang.String",
                                                                              "java.lang.String" },
                                        new Object[] { docId, libCode, compCode });
    }
}
