package com.zypg.cms.work.model.am.client;

import com.zypg.cms.work.model.am.common.CommonAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 03 18:54:18 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommonAMClient extends ApplicationModuleImpl implements CommonAM {
    /**
     * This is the default constructor (do not remove).
     */
    public CommonAMClient() {
    }

    public void insertGatherMonitorRecord(oracle.jbo.domain.Number docId, String fileName, String filePath) {
        Object _ret =
            this.riInvokeExportedMethod(this,"insertGatherMonitorRecord",new String [] {"oracle.jbo.domain.Number","java.lang.String","java.lang.String"},new Object[] {docId, fileName, filePath});
        return;
    }
}
