package com.zypg.cms.work.model.am.client;

import com.zypg.cms.work.model.am.common.TeachingPlanAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 27 10:40:51 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TeachingPlanAMClient extends ApplicationModuleImpl implements TeachingPlanAM {
    /**
     * This is the default constructor (do not remove).
     */
    public TeachingPlanAMClient() {
    }

    public void initTeachingplanInfo4View(oracle.jbo.domain.Number docId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"initTeachingplanInfo4View",new String [] {"oracle.jbo.domain.Number"},new Object[] {docId});
        return;
    }
}
