package com.zypg.cms.work.model.viewobject.resexp.query;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 20 14:06:48 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CmsResTemplateVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CmsResTemplateVOImpl() {
    }

    /**
     * Returns the bind variable value for bvUserId.
     * @return bind variable value for bvUserId
     */
    public Number getbvUserId() {
        return (Number)getNamedWhereClauseParam("bvUserId");
    }

    /**
     * Sets <code>value</code> for bind variable bvUserId.
     * @param value value to bind as bvUserId
     */
    public void setbvUserId(Number value) {
        setNamedWhereClauseParam("bvUserId", value);
    }

    /**
     * Returns the variable value for bvCategoryCode.
     * @return variable value for bvCategoryCode
     */
    public String getbvCategoryCode() {
        return (String)ensureVariableManager().getVariableValue("bvCategoryCode");
    }

    /**
     * Sets <code>value</code> for variable bvCategoryCode.
     * @param value value to bind as bvCategoryCode
     */
    public void setbvCategoryCode(String value) {
        ensureVariableManager().setVariableValue("bvCategoryCode", value);
    }

    /**
     * Returns the variable value for bvCompCode.
     * @return variable value for bvCompCode
     */
    public String getbvCompCode() {
        return (String)ensureVariableManager().getVariableValue("bvCompCode");
    }

    /**
     * Sets <code>value</code> for variable bvCompCode.
     * @param value value to bind as bvCompCode
     */
    public void setbvCompCode(String value) {
        ensureVariableManager().setVariableValue("bvCompCode", value);
    }
}
