package com.zypg.cms.admin.model.viewobject.query;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AssociationDefImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 16 10:57:53 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CmsFirstLevelLibVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CmsFirstLevelLibVOImpl() {
    }

    /**
     * Returns the bind variable value for bvCompCode.
     * @return bind variable value for bvCompCode
     */
    public String getbvCompCode() {
        return (String)getNamedWhereClauseParam("bvCompCode");
    }

    /**
     * Sets <code>value</code> for bind variable bvCompCode.
     * @param value value to bind as bvCompCode
     */
    public void setbvCompCode(String value) {
        setNamedWhereClauseParam("bvCompCode", value);
    }

    /**
     * Returns the bind variable value for bvRoleId.
     * @return bind variable value for bvRoleId
     */
    public Number getbvRoleId() {
        return (Number)getNamedWhereClauseParam("bvRoleId");
    }

    /**
     * Sets <code>value</code> for bind variable bvRoleId.
     * @param value value to bind as bvRoleId
     */
    public void setbvRoleId(Number value) {
        setNamedWhereClauseParam("bvRoleId", value);
    }

    protected ViewRowSetImpl createViewLinkAccessorRS(AssociationDefImpl associationDefImpl,
                                                      ViewObjectImpl viewObjectImpl, Row row, Object[] object) {
        
//        CmsSecondLevelLibVOImpl secondVo = (CmsSecondLevelLibVOImpl)viewObjectImpl;
//        secondVo.setbvRoleId(this.getbvRoleId());
//        secondVo.executeQuery();
        return super.createViewLinkAccessorRS(associationDefImpl, viewObjectImpl, row, object);
    }
}
