package com.zypg.cms.admin.model.viewobject.query;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 18 18:20:39 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CmsResDownloadVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ResId {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getResId();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setResId((Number)value);
            }
        }
        ,
        ResCode {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getResCode();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setResCode((String)value);
            }
        }
        ,
        ResName {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getResName();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setResName((String)value);
            }
        }
        ,
        ResTypeCode {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getResTypeCode();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setResTypeCode((String)value);
            }
        }
        ,
        ResTypeSimpleCode {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getResTypeSimpleCode();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setResTypeSimpleCode((String)value);
            }
        }
        ,
        ResTypeName {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getResTypeName();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setResTypeName((String)value);
            }
        }
        ,
        LibCode {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getLibCode();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setLibCode((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Seq {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getSeq();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setSeq((Number)value);
            }
        }
        ,
        Seq2 {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getSeq2();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setSeq2((Number)value);
            }
        }
        ,
        IsNo {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getIsNo();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setIsNo((Boolean)value);
            }
        }
        ,
        IsAuth {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getIsAuth();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setIsAuth((Boolean)value);
            }
        }
        ,
        IsFree {
            public Object get(CmsResDownloadVORowImpl obj) {
                return obj.getIsFree();
            }

            public void put(CmsResDownloadVORowImpl obj, Object value) {
                obj.setIsFree((Boolean)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CmsResDownloadVORowImpl object);

        public abstract void put(CmsResDownloadVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RESID = AttributesEnum.ResId.index();
    public static final int RESCODE = AttributesEnum.ResCode.index();
    public static final int RESNAME = AttributesEnum.ResName.index();
    public static final int RESTYPECODE = AttributesEnum.ResTypeCode.index();
    public static final int RESTYPESIMPLECODE = AttributesEnum.ResTypeSimpleCode.index();
    public static final int RESTYPENAME = AttributesEnum.ResTypeName.index();
    public static final int LIBCODE = AttributesEnum.LibCode.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int SEQ = AttributesEnum.Seq.index();
    public static final int SEQ2 = AttributesEnum.Seq2.index();
    public static final int ISNO = AttributesEnum.IsNo.index();
    public static final int ISAUTH = AttributesEnum.IsAuth.index();
    public static final int ISFREE = AttributesEnum.IsFree.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CmsResDownloadVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ResId.
     * @return the ResId
     */
    public Number getResId() {
        return (Number) getAttributeInternal(RESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResId.
     * @param value value to set the  ResId
     */
    public void setResId(Number value) {
        setAttributeInternal(RESID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ResCode.
     * @return the ResCode
     */
    public String getResCode() {
        return (String) getAttributeInternal(RESCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResCode.
     * @param value value to set the  ResCode
     */
    public void setResCode(String value) {
        setAttributeInternal(RESCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ResName.
     * @return the ResName
     */
    public String getResName() {
        return (String) getAttributeInternal(RESNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResName.
     * @param value value to set the  ResName
     */
    public void setResName(String value) {
        setAttributeInternal(RESNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ResTypeCode.
     * @return the ResTypeCode
     */
    public String getResTypeCode() {
        return (String) getAttributeInternal(RESTYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResTypeCode.
     * @param value value to set the  ResTypeCode
     */
    public void setResTypeCode(String value) {
        setAttributeInternal(RESTYPECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ResTypeSimpleCode.
     * @return the ResTypeSimpleCode
     */
    public String getResTypeSimpleCode() {
        return (String) getAttributeInternal(RESTYPESIMPLECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResTypeSimpleCode.
     * @param value value to set the  ResTypeSimpleCode
     */
    public void setResTypeSimpleCode(String value) {
        setAttributeInternal(RESTYPESIMPLECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ResTypeName.
     * @return the ResTypeName
     */
    public String getResTypeName() {
        return (String) getAttributeInternal(RESTYPENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResTypeName.
     * @param value value to set the  ResTypeName
     */
    public void setResTypeName(String value) {
        setAttributeInternal(RESTYPENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LibCode.
     * @return the LibCode
     */
    public String getLibCode() {
        return (String) getAttributeInternal(LIBCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LibCode.
     * @param value value to set the  LibCode
     */
    public void setLibCode(String value) {
        setAttributeInternal(LIBCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute1.
     * @param value value to set the  Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute2.
     * @param value value to set the  Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Seq.
     * @return the Seq
     */
    public Number getSeq() {
        return (Number) getAttributeInternal(SEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Seq.
     * @param value value to set the  Seq
     */
    public void setSeq(Number value) {
        setAttributeInternal(SEQ, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Seq2.
     * @return the Seq2
     */
    public Number getSeq2() {
        return (Number) getAttributeInternal(SEQ2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Seq2.
     * @param value value to set the  Seq2
     */
    public void setSeq2(Number value) {
        setAttributeInternal(SEQ2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsNo.
     * @return the IsNo
     */
    public Boolean getIsNo() {
        return (Boolean) getAttributeInternal(ISNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsNo.
     * @param value value to set the  IsNo
     */
    public void setIsNo(Boolean value) {
        setAttributeInternal(ISNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsAuth.
     * @return the IsAuth
     */
    public Boolean getIsAuth() {
        return (Boolean) getAttributeInternal(ISAUTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsAuth.
     * @param value value to set the  IsAuth
     */
    public void setIsAuth(Boolean value) {
        setAttributeInternal(ISAUTH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsFree.
     * @return the IsFree
     */
    public Boolean getIsFree() {
        return (Boolean) getAttributeInternal(ISFREE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsFree.
     * @param value value to set the  IsFree
     */
    public void setIsFree(Boolean value) {
        setAttributeInternal(ISFREE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
