package com.zypg.cms.admin.model.viewobject.query;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 16 18:13:10 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CmsResType4WPVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ResTypeCode {
            public Object get(CmsResType4WPVORowImpl obj) {
                return obj.getResTypeCode();
            }

            public void put(CmsResType4WPVORowImpl obj, Object value) {
                obj.setResTypeCode((String)value);
            }
        },
        ResTypeName {
            public Object get(CmsResType4WPVORowImpl obj) {
                return obj.getResTypeName();
            }

            public void put(CmsResType4WPVORowImpl obj, Object value) {
                obj.setResTypeName((String)value);
            }
        },
        LibCode {
            public Object get(CmsResType4WPVORowImpl obj) {
                return obj.getLibCode();
            }

            public void put(CmsResType4WPVORowImpl obj, Object value) {
                obj.setLibCode((String)value);
            }
        },
        IsSelected {
            public Object get(CmsResType4WPVORowImpl obj) {
                return obj.getIsSelected();
            }

            public void put(CmsResType4WPVORowImpl obj, Object value) {
                obj.setIsSelected((Boolean)value);
            }
        },
        CmsRes4WPVO {
            public Object get(CmsResType4WPVORowImpl obj) {
                return obj.getCmsRes4WPVO();
            }

            public void put(CmsResType4WPVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CmsResType4WPVORowImpl object);

        public abstract void put(CmsResType4WPVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RESTYPECODE = AttributesEnum.ResTypeCode.index();
    public static final int RESTYPENAME = AttributesEnum.ResTypeName.index();
    public static final int LIBCODE = AttributesEnum.LibCode.index();
    public static final int ISSELECTED = AttributesEnum.IsSelected.index();
    public static final int CMSRES4WPVO = AttributesEnum.CmsRes4WPVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CmsResType4WPVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ResTypeCode.
     * @return the ResTypeCode
     */
    public String getResTypeCode() {
        return (String)getAttributeInternal(RESTYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResTypeCode.
     * @param value value to set the  ResTypeCode
     */
    public void setResTypeCode(String value) {
        setAttributeInternal(RESTYPECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ResTypeName.
     * @return the ResTypeName
     */
    public String getResTypeName() {
        return (String)getAttributeInternal(RESTYPENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResTypeName.
     * @param value value to set the  ResTypeName
     */
    public void setResTypeName(String value) {
        setAttributeInternal(RESTYPENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LibCode.
     * @return the LibCode
     */
    public String getLibCode() {
        return (String)getAttributeInternal(LIBCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LibCode.
     * @param value value to set the  LibCode
     */
    public void setLibCode(String value) {
        setAttributeInternal(LIBCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsSelected.
     * @return the IsSelected
     */
    public Boolean getIsSelected() {
        Boolean flag = false;
        RowIterator iter = this.getCmsRes4WPVO();
        if(iter != null)
            for(Row rw: iter.getAllRowsInRange()){
                  Boolean isSelected = (Boolean)rw.getAttribute("IsSelected");
                if(isSelected){
                      flag = true;
                      break;
                    }
                } 
        return flag;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsSelected.
     * @param value value to set the  IsSelected
     */
    public void setIsSelected(Boolean value) {
//        if (value == null) {
//            setAttributeInternal(ISSELECTED, false);
//        } else {
//            setAttributeInternal(ISSELECTED, value);
//        }
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CmsRes4WPVO.
     */
    public RowIterator getCmsRes4WPVO() {
        RowIterator iter = (RowIterator)getAttributeInternal(CMSRES4WPVO);
        iter.setRangeStart(0);
        return iter;
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
