SELECT
  c.DOCLIBID,
  c.DIV_NAME,
  com.com_name,
  com.COM_CLASS,
  vm.VM_KEY,
  vm.VM_PATH
FROM
  PUB_PAGECOM_CONFIG c,
  PUB_COM_CONFIG com,
  PUB_VM_CONFIG vm
WHERE
  c.DOCLIBID = 21
AND c.DIV_NAME = 'FilterDiv'
AND c.COMID = com.COMID
AND c.RELATIONID = vm.RELATIONID
ORDER BY
  COM_INDEX;

SELECT
  A.RELATIONID,
  A.COM_INDEX,
  A.COMID,
  A.DOMAINID,
  B.COM_NAME,
  B.COM_CODE,
  B.COM_CLASS
FROM
  PUB_PAGECOM_CONFIG A,
  PUB_COM_CONFIG B
WHERE
  A.COMID = B.COMID
AND A.DOCLIBID = 21
AND A.DIV_NAME = 'ListDiv'
ORDER BY
  A.COM_INDEX;

SELECT
    VM_KEY,
    VM_PATH
  FROM
    PUB_VM_CONFIG
  WHERE
    RELATIONID =?
