catch {OMBDROP TABLE 'CMS_3RD_AUTHORIZATION_ITEM_T'}

OMBCREATE TABLE 'CMS_3RD_AUTHORIZATION_ITEM_T' \
ADD COLUMN 'ITEM_ID' \
SET PROPERTIES \
(DATATYPE, NOT_NULL) \
VALUES \
('NUMBER', '1') \
ADD COLUMN 'ORDER_ID' \
SET PROPERTIES \
(DATATYPE, NOT_NULL) \
VALUES \
('NUMBER', '0') \
ADD COLUMN 'SALES_TOTAL_COST' \
SET PROPERTIES \
(PRECISION, SCALE, DATATYPE, NOT_NULL) \
VALUES \
('9', '2', 'NUMBER', '0') \
ADD COLUMN 'SALES_TOTAL_NUM' \
SET PROPERTIES \
(DATATYPE, NOT_NULL) \
VALUES \
('NUMBER', '0') \
ADD COLUMN 'OBJECT_VERSION_NUMBER' \
SET PROPERTIES \
(DATATYPE, NOT_NULL) \
VALUES \
('NUMBER', '0') \
ADD COLUMN 'CREATED_BY' \
SET PROPERTIES \
(DATATYPE, NOT_NULL) \
VALUES \
('NUMBER', '0') \
ADD COLUMN 'CREATION_DATE' \
SET PROPERTIES \
(DATATYPE, NOT_NULL) \
VALUES \
('DATE', '0') \
ADD COLUMN 'LAST_UPDATED_BY' \
SET PROPERTIES \
(DATATYPE, NOT_NULL) \
VALUES \
('NUMBER', '0') \
ADD COLUMN 'LAST_UPDATE_DATE' \
SET PROPERTIES \
(DATATYPE, NOT_NULL) \
VALUES \
('DATE', '0') \
ADD COLUMN 'ATTRIBUTE1' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE2' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE3' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE4' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE5' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE6' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE7' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE8' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE9' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE10' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE11' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE12' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE13' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE14' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ATTRIBUTE15' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('240', 'VARCHAR2', '0') \
ADD COLUMN 'ORDER_DOC_ID' \
SET PROPERTIES \
(DATATYPE, NOT_NULL) \
VALUES \
('NUMBER', '0') \
ADD COLUMN 'AUTHOR_DOC_ID' \
SET PROPERTIES \
(DATATYPE, NOT_NULL) \
VALUES \
('NUMBER', '0') \
ADD COLUMN 'EXCLUSIVE_COPYRIGHT_FLAG' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('20', 'VARCHAR2', '0') \
ADD COLUMN 'COMP_CODE' \
SET PROPERTIES \
(LENGTH, DATATYPE, NOT_NULL) \
VALUES \
('20', 'VARCHAR2', '0') \
ADD PRIMARY_KEY 'CMS_3RD_AUTHORIZATION_ITE_PK' \
SET PROPERTIES \
(ENABLECONSTRAINT) \
VALUES \
('ENABLE') \
SET REF COLUMNS ( 'ITEM_ID') \
ADD INDEX 'CMS_3RD_AUTHORIZATION_ITE_PK' \
SET PROPERTIES \
(INDEX_TYPE, PARALLEL_ACCESS_MODE, PARALLEL_DEGREE) \
VALUES \
('UNIQUE', 'PARALLEL', '1') \
ADD INDEX_COLUMN 'ITEM_ID' OF INDEX 'CMS_3RD_AUTHORIZATION_ITE_PK' 
