SET SQLBLANKLINES ON
CREATE TABLE CMS_PERIODICAL_SETUP_T 
(
  SETUP_ID DECIMAL(2) NOT NULL 
, PERIODICAL_CATEGORY_ID VARCHAR2(80) 
, PERIODICAL_TYPE VARCHAR2(40) 
, PAPER_TYPE VARCHAR2(40) 
, CHIEF_EDITOR VARCHAR2(80) 
, PRICE NUMBER(2) 
, BOOK_SIZE VARCHAR2(40) 
, CN VARCHAR2(40) 
, ISSN VARCHAR2(40) 
, WORDS VARCHAR2(20) 
, PROD_SIZE VARCHAR2(40) 
, COMP_CODE VARCHAR2(40) 
, READER_GROUP VARCHAR2(40) 
, ORG VARCHAR2(80) 
, PUBLISHING VARCHAR2(80) 
, DESCRIPTION VARCHAR2(480) 
, DATENUM1 NUMBER 
, DATENUM2 NUMBER 
, DATENUM3 NUMBER 
, DATENUM4 NUMBER 
, DATENUM5 NUMBER 
, DATENUM6 NUMBER 
, DATENUM7 NUMBER 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, TOTAL NUMBER 
, LANG VARCHAR2(40) 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_PERIODICAL_SETUP_T_PK PRIMARY KEY 
  (
    SETUP_ID 
  )
  ENABLE 
);

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.SETUP_ID IS '设置ID，主键。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.PERIODICAL_CATEGORY_ID IS '期刊ID，来源于分类表。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.PAPER_TYPE IS '用纸类型，来源于LOOKUP。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.CHIEF_EDITOR IS '主编。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.PRICE IS '定价。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.CN IS 'CN。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.ISSN IS 'ISSN。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.WORDS IS '版字数。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.PROD_SIZE IS '成品尺寸。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.COMP_CODE IS '出版社。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.ORG IS '主管单位。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.PUBLISHING IS '出版发行。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DESCRIPTION IS '刊物描述。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM1 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM2 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM3 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM4 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM5 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM6 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM7 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';
