SET SQLBLANKLINES ON
CREATE TABLE CMS_EXTEND_ATTR_STORAGE_T 
(
  STORAGE_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, EXTEND_ATTRS CLOB 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_EXTEND_ATTR_STORAGE_T_PK PRIMARY KEY 
  (
    STORAGE_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_EXTEND_ATTR_T 
(
  EXTEND_ATTR_ID NUMBER NOT NULL 
, ATTR_CODE VARCHAR2(100) 
, ATTR_MEANING VARCHAR2(20) 
, ATTR_TYPE VARCHAR2(40) 
, COMP_CODE VARCHAR2(40) 
, LIB_CODE VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_EXTEND_ATTR_T_PK PRIMARY KEY 
  (
    EXTEND_ATTR_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_EXTEND_VALUE_LIST_T 
(
  LIST_ID NUMBER NOT NULL 
, VALUE_CODE VARCHAR2(40) 
, VALUE_MEANING VARCHAR2(40) 
, EXTEND_ATTR_ID NUMBER 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_EXTEND_VALUE_LIST_T_PK PRIMARY KEY 
  (
    LIST_ID 
  )
  ENABLE 
);

COMMENT ON COLUMN CMS_EXTEND_ATTR_STORAGE_T.STORAGE_ID IS '主键ID';

COMMENT ON COLUMN CMS_EXTEND_ATTR_STORAGE_T.DOC_ID IS '文档ID';

COMMENT ON COLUMN CMS_EXTEND_ATTR_STORAGE_T.EXTEND_ATTRS IS '扩展字段JSON串';

COMMENT ON COLUMN CMS_EXTEND_ATTR_T.EXTEND_ATTR_ID IS '主键ID';

COMMENT ON COLUMN CMS_EXTEND_ATTR_T.ATTR_CODE IS '字段CODE';

COMMENT ON COLUMN CMS_EXTEND_ATTR_T.ATTR_MEANING IS '字段含义';

COMMENT ON COLUMN CMS_EXTEND_ATTR_T.ATTR_TYPE IS '字段类型';

COMMENT ON COLUMN CMS_EXTEND_ATTR_T.COMP_CODE IS '分社代码';

COMMENT ON COLUMN CMS_EXTEND_ATTR_T.LIB_CODE IS '库代码';

COMMENT ON COLUMN CMS_EXTEND_VALUE_LIST_T.LIST_ID IS '主键ID';

COMMENT ON COLUMN CMS_EXTEND_VALUE_LIST_T.VALUE_CODE IS '值列表CODE';

COMMENT ON COLUMN CMS_EXTEND_VALUE_LIST_T.VALUE_MEANING IS '值列表含义';

COMMENT ON COLUMN CMS_EXTEND_VALUE_LIST_T.EXTEND_ATTR_ID IS '关联的扩展字段ID';

CREATE SEQUENCE CMS_EXTEND_ATTR_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_EXTEND_ATTR_STORAGE_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_EXTEND_VALUE_LIST_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;
