package com.zypg.cms.work.model.viewobject.attach;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 07 17:18:48 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CmsAttachTVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CmsAttachTVOImpl() {
    }


    /**
     * Returns the variable value for bvScourceDocId.
     * @return variable value for bvScourceDocId
     */
    public Number getbvScourceDocId() {
        return (Number)ensureVariableManager().getVariableValue("bvScourceDocId");
    }

    /**
     * Sets <code>value</code> for variable bvScourceDocId.
     * @param value value to bind as bvScourceDocId
     */
    public void setbvScourceDocId(Number value) {
        ensureVariableManager().setVariableValue("bvScourceDocId", value);
    }
}
