SET SQLBLANKLINES ON
CREATE TABLE CMS_3RD_AUTHORIZATION_ITEMS_T 
(
  ITEMS_ID NUMBER NOT NULL 
, ITEM_ID NUMBER 
, SALES_COST NUMBER(9, 2) 
, SALES_NUM NUMBER 
, IMPORT_DATE DATE 
, REMARKS VARCHAR2(400) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_3RD_AUTHORIZATION_ITE_PK1 PRIMARY KEY 
  (
    ITEMS_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_3RD_AUTHORIZATION_ITEM_T 
(
  ITEM_ID NUMBER NOT NULL 
, ORDER_ID NUMBER 
, SALES_TOTAL_COST NUMBER(9, 2) 
, SALES_TOTAL_NUM NUMBER 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, ORDER_DOC_ID NUMBER 
, AUTHOR_DOC_ID NUMBER 
, EXCLUSIVE_COPYRIGHT_FLAG VARCHAR2(20) 
, COMP_CODE VARCHAR2(20) 
, CONSTRAINT CMS_3RD_AUTHORIZATION_ITE_PK PRIMARY KEY 
  (
    ITEM_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_3RD_AUTHORIZATION_ORDER_T 
(
  ORDER_ID NUMBER NOT NULL 
, COPYRIGHT_ID NUMBER 
, ORDER_NAME VARCHAR2(80) 
, AUTHORIZED_COMPANY NUMBER 
, AUTHORIZED_TYPE VARCHAR2(20) 
, AUTHORIZED_FILE_TYPE VARCHAR2(20) 
, AUTHORIZED_START_TIME DATE 
, AUTHORIZED_VALID_PERIOD VARCHAR2(20) 
, AUTHORIZED_LANG VARCHAR2(500) 
, AUTHORIZED_AREA VARCHAR2(500) 
, INCLUDE_PUBLIC_COPYRIGHT_FLAG VARCHAR2(20) 
, REMARKS VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, DOC_ID NUMBER 
, CONSTRAINT CMS_3RD_AUTHORIZATION_LIS_PK PRIMARY KEY 
  (
    ORDER_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_ACTIVITY_T 
(
  ACTIVITY_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, ACTIVITY_THEME VARCHAR2(200) 
, ACTIVITY_START_TIME DATE 
, ACTIVITY_END_TIME DATE 
, ACTIVITY_LOCATION VARCHAR2(200) 
, ACTIVITY_TYPE VARCHAR2(40) 
, COMP_CODE VARCHAR2(20) 
, ACTIVITY_STORE_TIME DATE 
, ACTIVITY_DESC VARCHAR2(4000) 
, REMARKS VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_ACTIVITY_T_PK PRIMARY KEY 
  (
    ACTIVITY_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_ATTACH_T 
(
  ATTACH_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, SOURCE_ID VARCHAR2(240) 
, PATH VARCHAR2(80) 
, TITLE VARCHAR2(240) 
, ATTACH_TYPE VARCHAR2(80) 
, REMARKS VARCHAR2(80) 
, FORMAT VARCHAR2(80) 
, FILE_SIZE NUMBER 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, UCM_DID NUMBER 
, UCM_DOCNAME VARCHAR2(80) 
, CONSTRAINT CMS_ATTACH_T_PK PRIMARY KEY 
  (
    ATTACH_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_AUDIO_T 
(
  AUDIO_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, FILE_NAME VARCHAR2(240 BYTE) 
, SERIES_NAME VARCHAR2(240 BYTE) 
, ISBN VARCHAR2(80 BYTE) 
, ITEM_CODE VARCHAR2(40 BYTE) 
, AUDIO_TYPE VARCHAR2(40 BYTE) 
, CARRIER_TYPE VARCHAR2(40 BYTE) 
, LANG VARCHAR2(20 BYTE) 
, EDITOR VARCHAR2(80 BYTE) 
, TEXT_EDITOR VARCHAR2(80 BYTE) 
, RECORD_USER VARCHAR2(80 BYTE) 
, PUB_TIME DATE 
, ASSORT_BOOK VARCHAR2(80 BYTE) 
, DEPT_CODE VARCHAR2(40 BYTE) 
, KEYWORD VARCHAR2(1000 BYTE) 
, CONTENT_DESC VARCHAR2(2000 BYTE) 
, REMARKS VARCHAR2(2000 BYTE) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240 BYTE) 
, ATTRIBUTE2 VARCHAR2(240 BYTE) 
, ATTRIBUTE3 VARCHAR2(240 BYTE) 
, ATTRIBUTE4 VARCHAR2(240 BYTE) 
, ATTRIBUTE5 VARCHAR2(240 BYTE) 
, ATTRIBUTE6 VARCHAR2(240 BYTE) 
, ATTRIBUTE7 VARCHAR2(240 BYTE) 
, ATTRIBUTE8 VARCHAR2(240 BYTE) 
, ATTRIBUTE9 VARCHAR2(240 BYTE) 
, ATTRIBUTE10 VARCHAR2(240 BYTE) 
, ATTRIBUTE11 VARCHAR2(240 BYTE) 
, ATTRIBUTE12 VARCHAR2(240 BYTE) 
, ATTRIBUTE13 VARCHAR2(240 BYTE) 
, ATTRIBUTE14 VARCHAR2(240 BYTE) 
, ATTRIBUTE15 VARCHAR2(240 BYTE) 
, FILE_FORMAT VARCHAR2(20) 
, FILE_SIZE VARCHAR2(20) 
, FILE_TIME VARCHAR2(20) 
, FILE_STORE_TIME DATE 
, PREVIEW_URL VARCHAR2(480) 
, SCRIPT CLOB 
, CONSTRAINT CMS_AUDIO_T_PK PRIMARY KEY 
  (
    AUDIO_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE CMS_AUTHOR_COPYRIGHT_T 
(
  COPYRIGHT_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, BOOK_DOC_ID NUMBER 
, COPYRIGHT_FORM VARCHAR2(80) 
, EXCLUSIVE_COPYRIGHT_FLAG VARCHAR2(20) 
, PART_PROBATION_FLAG VARCHAR2(20) 
, PUBLIC_COPYRIGHT_FLAG VARCHAR2(20) 
, COPYRIGHT_OWNER VARCHAR2(80) 
, COPYRIGHT_AGENT VARCHAR2(80) 
, E_BOOK_PRICE NUMBER(9, 2) 
, E_BOOK_MIN_PRICE NUMBER(9, 2) 
, AUTHORIZED_AREA VARCHAR2(500) 
, AUTHORIZED_LANG VARCHAR2(500) 
, COPYRIGHT_REGISTRATION_NUMBER VARCHAR2(100) 
, OVERSEAS_COPYRIGHT_FLAG VARCHAR2(20) 
, OVERSEAS_ROYALTY VARCHAR2(80) 
, DIGITAL_ROYALTY VARCHAR2(80) 
, PAPER_MEDIUM_COPYRIGHT_FLAG VARCHAR2(20) 
, PAPER_MEDIUM_START_TIME DATE 
, PAPER_MEDIUM_END_TIME DATE 
, ELECTRONIC_COPYRIGHT_FLAG VARCHAR2(20) 
, ELECTRONIC_START_TIME DATE 
, ELECTRONIC_END_TIME DATE 
, AUDIO_VIDEO_COPYRIGHT_FLAG VARCHAR2(20) 
, AUDIO_VIDEO_START_TIME DATE 
, AUDIO_VIDEO_END_TIME DATE 
, NETWORK_COPYRIGHT_FLAG VARCHAR2(20) 
, NETWORK_START_TIME DATE 
, NETWORK_END_TIME DATE 
, BROADCAST_COPYRIGHT_FLAG VARCHAR2(20) 
, BROADCAST_START_TIME DATE 
, BROADCAST_END_TIME DATE 
, COPYRIGHT_CIP VARCHAR2(4000) 
, REMARKS VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, BOOK_NAME VARCHAR2(40) 
, ISBN VARCHAR2(40) 
, AUTHOR VARCHAR2(40) 
, EDITOR VARCHAR2(80) 
, TRANSLATOR VARCHAR2(80) 
, PRICE NUMBER(9, 2) 
, CONSTRAINT CMS_AUTHOR_COPYRIGHT_T_PK PRIMARY KEY 
  (
    COPYRIGHT_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_BOOK_T 
(
  BOOK_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, BOOK_NAME VARCHAR2(240) 
, ISBN VARCHAR2(80) 
, SERIES VARCHAR2(240) 
, ITEM_CODE VARCHAR2(40) 
, LANG VARCHAR2(20) 
, EDITOR VARCHAR2(80) 
, FORMAT_DESIGN VARCHAR2(80) 
, COVER_DESIGN VARCHAR2(80) 
, AUTHOR VARCHAR2(80) 
, CHIEF_EDITOR VARCHAR2(80) 
, TRANSLATOR VARCHAR2(80) 
, PUB_TIME DATE 
, PUBLISHING_HOUSE VARCHAR2(80) 
, IMPRESSION NUMBER 
, EDITION NUMBER 
, PAGINATION NUMBER 
, PRICE NUMBER(9, 2) 
, KEYWORD VARCHAR2(4000) 
, READER_GROUP VARCHAR2(40) 
, SUGGESTION VARCHAR2(4000) 
, PROD_SIZE VARCHAR2(40) 
, COLOR_NUM VARCHAR2(40) 
, COVER_TYPESET VARCHAR2(40) 
, ASSORT_PROD VARCHAR2(40) 
, REMARKS VARCHAR2(4000) 
, BOOK_SIZE VARCHAR2(40) 
, MAIN_PAGE VARCHAR2(40) 
, MAIN_TYPESET VARCHAR2(40) 
, FORMAT_COMP VARCHAR2(80) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_BOOK_T_PK PRIMARY KEY 
  (
    BOOK_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_CATEGORY_T 
(
  CATEGORY_ID NUMBER NOT NULL 
, CATEGORY_NAME VARCHAR2(80) 
, PARENT_NODE_TYPE VARCHAR2(20) 
, PARENT_NODE_ID NUMBER 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, SEQ NUMBER 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT PM_CATEGORY_T_PK PRIMARY KEY 
  (
    CATEGORY_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_CHAPTER_T 
(
  CHAPTER_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, CHAPTER_CODE VARCHAR2(40) 
, CHAPTER_NAME VARCHAR2(480) 
, CONTENT CLOB 
, SEQ NUMBER 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_CHAPTER_T_PK PRIMARY KEY 
  (
    CHAPTER_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_COMPANY_COPYRIGHT_T 
(
  COMPANY_ID NUMBER NOT NULL 
, COMPANY_NAME VARCHAR2(240) 
, COMPANY_ADDR VARCHAR2(240) 
, COMPANY_CONTACT VARCHAR2(80) 
, COMPANY_PHONE VARCHAR2(80) 
, REMARKS VARCHAR2(80) 
, COMP_CODE VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_COMPANY_COPYRIGHT_T_PK PRIMARY KEY 
  (
    COMPANY_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_COMP_LIB_REL_T 
(
  REL_ID NUMBER NOT NULL 
, COMP_CODE VARCHAR2(40) 
, LIB_CODE VARCHAR2(40) 
, LIB_TYPE_CODE VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_COMP_LIB_REL_T_PK PRIMARY KEY 
  (
    REL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_COURSEWARE_T 
(
  COURSEWARE_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, TEACHING_MATERIAL_NAME VARCHAR2(200) 
, TEACHING_MATERIAL_ISBN VARCHAR2(80) 
, TEACHING_MATERIAL_AUTHOR VARCHAR2(80) 
, TEACHING_MATERIAL_EDITOR VARCHAR2(80) 
, TEACHING_MATERIAL_SERIES_NAME VARCHAR2(80) 
, TEACHING_MATERIAL_TYPE VARCHAR2(40) 
, COMP_CODE VARCHAR2(20) 
, COURSEWARE_TYPE VARCHAR2(40) 
, COURSEWARE_NAME VARCHAR2(80) 
, COPYRIGHT_FLAG VARCHAR2(20) 
, KEYWORD VARCHAR2(1000) 
, REMARKS VARCHAR2(4000) 
, UPLOAD_TIME DATE 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, SOURCE_BOOK_DOC_ID NUMBER 
, CONSTRAINT CMS_COURSEWARE_T_PK PRIMARY KEY 
  (
    COURSEWARE_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_DOCBOOK_JOB_T 
(
  JOB_ID NUMBER NOT NULL 
, JOB_NAME VARCHAR2(480) 
, COMP_CODE VARCHAR2(40) 
, ISBN VARCHAR2(80) 
, STATUS VARCHAR2(40) 
, RESULT VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_DOCBOOK_IMP_JOB_T_PK PRIMARY KEY 
  (
    JOB_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_DOCBOOK_MONITOR_T 
(
  MONITOR_ID NUMBER NOT NULL 
, JOB_ID NUMBER 
, START_DATE DATE 
, END_DATE DATE 
, STATUS VARCHAR2(40) 
, RESULT VARCHAR2(40) 
, REMARKS VARCHAR2(240) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_DOCBOOK_IMP_MONITOR_T_PK PRIMARY KEY 
  (
    MONITOR_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_DOC_CATEGORY_REL_T 
(
  REL_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, CATEGORY_ID NUMBER 
, CATEGORY_GROUP_TYPE VARCHAR2(20) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_DOC_CATEGORY_REL_T_PK PRIMARY KEY 
  (
    REL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_DOC_GROUP_REL_T 
(
  REL_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, GROUP_ID NUMBER 
, INDEX_FLAG VARCHAR2(20) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_DOC_GROUP_REL_T_PK PRIMARY KEY 
  (
    REL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_DOC_REL_T 
(
  REL_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, PARENT_DOC_ID NUMBER 
, REL_TYPE VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_DOC_REL_T_PK PRIMARY KEY 
  (
    REL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_DOC_T 
(
  DOC_ID NUMBER NOT NULL 
, LIB_CODE VARCHAR2(40) 
, LIB_TYPE_CODE VARCHAR2(40) 
, COMP_CODE VARCHAR2(40) 
, STATUS VARCHAR2(40) 
, SOURCE_STATUS VARCHAR2(40) 
, THUMBNAIL_URL VARCHAR2(720) 
, DELETE_FLAG VARCHAR2(20) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CHAPTER_FLAG VARCHAR2(20) 
, CONSTRAINT CMS_DOC_T_PK PRIMARY KEY 
  (
    DOC_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_DOC_UCM_REL_T 
(
  REL_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, UCM_DID NUMBER 
, UCM_DOCNAME VARCHAR2(80) 
, FILE_NAME VARCHAR2(80) 
, FTP_PATH VARCHAR2(240) 
, FTP_UPLOAD_DATE VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, HAS_THUMBNAIL_FLAG VARCHAR2(20) 
, REF_DOC_ID NUMBER 
, DOC_TYPE VARCHAR2(40) 
, CONSTRAINT CMS_DOC_UCM_REL_T_PK PRIMARY KEY 
  (
    REL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_ELEC_PROD_T 
(
  ELEC_PROD_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, ELEC_PROD_NAME VARCHAR2(80) 
, ISBN VARCHAR2(40) 
, ITEM_CODE VARCHAR2(40) 
, ASSORT_BOOK VARCHAR2(80) 
, PROD_TYPE VARCHAR2(40) 
, PUBLISHING_HOUSE VARCHAR2(80) 
, LANG VARCHAR2(20) 
, CARRIER_TYPE VARCHAR2(20) 
, TIME_LENGTH VARCHAR2(40) 
, AMOUNT NUMBER 
, DISK_DESIGN VARCHAR2(80) 
, EDITOR VARCHAR2(80) 
, TEXT_EDITOR VARCHAR2(80) 
, PRODUCER VARCHAR2(80) 
, PUB_TIME DATE 
, COMP_CODE VARCHAR2(20) 
, KEYWORD VARCHAR2(1000) 
, CONTENT_DESC VARCHAR2(4000) 
, REMARKS VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, SCRIPT CLOB 
, CONSTRAINT CMS_ELEC_PROD_T_PK PRIMARY KEY 
  (
    ELEC_PROD_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_FIGURE_EXIF_INFO_T 
(
  INFO_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, IMAGE_DESCRIPTION VARCHAR2(1000) 
, MAKE VARCHAR2(100) 
, MODEL VARCHAR2(100) 
, ORIENTATION VARCHAR2(100) 
, X_RESOLUTION VARCHAR2(100) 
, Y_RESOLUTION VARCHAR2(100) 
, RESOLUTION_UNIT VARCHAR2(100) 
, DATE_TIME VARCHAR2(100) 
, YCBCR_POSITIONING VARCHAR2(100) 
, EXPOSURE_TIME VARCHAR2(100) 
, F_NUMBER VARCHAR2(100) 
, ISO_SPEED_RATINGS VARCHAR2(100) 
, EXIF_VERSION VARCHAR2(100) 
, DATE_TIME_ORIGINAL VARCHAR2(100) 
, DATE_TIME_DIGITIZED VARCHAR2(100) 
, COMPONENTS_CONFIGURATION VARCHAR2(100) 
, COMPRESSED_BITS_PER_PIXEL VARCHAR2(100) 
, SHUTTER_SPEED_VALUE VARCHAR2(100) 
, APERTURE_VALUE VARCHAR2(100) 
, EXPOSURE_BIAS_VALUE VARCHAR2(100) 
, MAX_APERTURE_VALUE VARCHAR2(100) 
, METERING_MODE VARCHAR2(100) 
, FLASH VARCHAR2(100) 
, FOCAL_LENGTH VARCHAR2(100) 
, USER_COMMENT VARCHAR2(200) 
, FLASHPIX_VERSION VARCHAR2(100) 
, COLOR_SPACE VARCHAR2(100) 
, EXIF_IMAGE_WIDTH VARCHAR2(100) 
, EXIF_IMAGE_HEIGHT VARCHAR2(100) 
, FOCAL_PLANE_X_RESOLUTION VARCHAR2(100) 
, FOCAL_PLANE_Y_RESOLUTION VARCHAR2(100) 
, FOCAL_PLANE_RESOLUTION_UNIT VARCHAR2(100) 
, SENSING_METHOD VARCHAR2(100) 
, FILE_SOURCE VARCHAR2(100) 
, CUSTOM_RENDERED VARCHAR2(100) 
, EXPOSURE_MODE VARCHAR2(100) 
, WHITE_BALANCE VARCHAR2(100) 
, DIGITAL_ZOOM_RATIO VARCHAR2(100) 
, SCENE_CAPTURE_TYPE VARCHAR2(100) 
, COMPRESSION VARCHAR2(100) 
, THUMBNAIL_OFFSET VARCHAR2(100) 
, THUMBNAIL_LENGTH VARCHAR2(100) 
, THUMBNAIL_DATA VARCHAR2(100) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_FIGURE_EXIF_INFO_T_PK PRIMARY KEY 
  (
    INFO_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_FIGURE_GROUP_T 
(
  GROUP_ID NUMBER NOT NULL 
, GROUP_NAME VARCHAR2(200) 
, GROUP_DESC VARCHAR2(4000) 
, LIB_CODE VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_FIGURE_GROUP_T_PK PRIMARY KEY 
  (
    GROUP_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_GATHER_MONITOR_T 
(
  MONITOR_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, FILE_NAME VARCHAR2(80) 
, FILE_PATH VARCHAR2(240) 
, RESULT VARCHAR2(20) 
, THUMBNAIL_RESULT VARCHAR2(20) 
, REMARKS VARCHAR2(20) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_GATHER_MONITOR_T_PK PRIMARY KEY 
  (
    MONITOR_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_ILLUSTRATION_T 
(
  ILLUSTRATION_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, ILLUSTRATION_NAME VARCHAR2(200) 
, ILLUSTRATION_SOURCE VARCHAR2(80) 
, ILLUSTRATION_TYPE VARCHAR2(40) 
, ILLUSTRATION_AUTHOR VARCHAR2(80) 
, MAP_APPROVE_NUM VARCHAR2(80) 
, PAGE_NUMBER VARCHAR2(20) 
, KEYWORD VARCHAR2(1000) 
, ILLUSTRATION_DESC VARCHAR2(4000) 
, REMARKS VARCHAR2(4000) 
, FIGURE_FORMAT VARCHAR2(20) 
, FIGURE_DIMENSION VARCHAR2(20) 
, FIGURE_SIZE VARCHAR2(20) 
, COVER_DESIGN VARCHAR2(80) 
, FIGURE_RESOLUTION VARCHAR2(80) 
, FIGURE_X_RESOLUTION VARCHAR2(80) 
, FIGURE_Y_RESOLUTION VARCHAR2(80) 
, FIGURE_WIDTH VARCHAR2(20) 
, FIGURE_HEIGHT VARCHAR2(20) 
, FIGURE_STORE_TIME DATE 
, COPYRIGHT_FLAG VARCHAR2(20) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_ILLUSTRATION_T_PK PRIMARY KEY 
  (
    ILLUSTRATION_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_JB_INFO_T 
(
  JB_INFO_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, BRIEF_INTRODUCTION CLOB 
, CATALOG CLOB 
, FOREWORD CLOB 
, POSTSCRIPT CLOB 
, HIGHLIGHTS CLOB 
, PREFACE CLOB 
, GLOSSARY CLOB 
, REFERENCES CLOB 
, AUTHOR_INTRODUCTION CLOB 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_JB_INFO_T_PK PRIMARY KEY 
  (
    JB_INFO_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_LIB_CATEGORY_G_REL_T 
(
  REL_ID NUMBER NOT NULL 
, CATEGORY_GROUP_CODE VARCHAR2(20) 
, LIB_CODE VARCHAR2(40) 
, LIB_TYPE_CODE VARCHAR2(20) 
, COMP_CODE VARCHAR2(20) 
, PRIMARY_FLAG VARCHAR2(10) 
, ENABLE_FLAG VARCHAR2(10) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_CATEGORY_GROUP_T_PK PRIMARY KEY 
  (
    REL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_LIB_RES_REL_T 
(
  REL_ID NUMBER NOT NULL 
, LIB_CODE VARCHAR2(40) 
, RES_CODE VARCHAR2(40) 
, RES_TYPE_CODE VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_LIB_RES_REL_T_PK PRIMARY KEY 
  (
    REL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_LOOKUP_TYPE_T 
(
  LOOKUP_TYPE_ID NUMBER NOT NULL 
, LOOKUP_TYPE_CODE VARCHAR2(40) 
, LOOKUP_TYPE_NAME VARCHAR2(20) 
, LOOKUP_TYPE_DESC VARCHAR2(20) 
, ENABLE_FLAG VARCHAR2(10) 
, MODULE_TYPE VARCHAR2(20) 
, MODULE_CODE VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, SEQ NUMBER 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_LOOKUP_TYPE_T_PK PRIMARY KEY 
  (
    LOOKUP_TYPE_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_LOOKUP_VALUE_T 
(
  LOOKUP_VALUE_ID NUMBER NOT NULL 
, LOOKUP_VALUE_CODE VARCHAR2(40) 
, LOOKUP_TYPE_CODE VARCHAR2(40) 
, MEANING VARCHAR2(80) 
, LOOKUP_VALUE_DESC VARCHAR2(240) 
, ENABLE_FLAG VARCHAR2(10) 
, OBJECT_VERSION_NUMBER VARCHAR2(20) 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, SEQ NUMBER 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_LOOKUP_VALUE_T_PK PRIMARY KEY 
  (
    LOOKUP_VALUE_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_MATERIAL_FIGURE_T 
(
  FIGURE_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, FIGURE_NAME VARCHAR2(240) 
, FIGURE_FORMAT VARCHAR2(20) 
, FIGURE_DIMENSION VARCHAR2(20) 
, FIGURE_SIZE VARCHAR2(20) 
, COVER_DESIGN VARCHAR2(80) 
, FIGURE_RESOLUTION VARCHAR2(80) 
, FIGURE_X_RESOLUTION VARCHAR2(80) 
, FIGURE_Y_RESOLUTION VARCHAR2(80) 
, FIGURE_WIDTH VARCHAR2(20) 
, FIGURE_HEIGHT VARCHAR2(20) 
, FIGURE_STORE_TIME DATE 
, FIGURE_CODE VARCHAR2(20) 
, SERIES_NAME VARCHAR2(240) 
, FIGURE_AUTHOR VARCHAR2(80) 
, FIGURE_TYPE VARCHAR2(40) 
, FIGURE_STYLE VARCHAR2(40) 
, COMP_CODE VARCHAR2(20) 
, KEYWORD VARCHAR2(1000) 
, FIGURE_DESC VARCHAR2(4000) 
, REMARKS VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_MATERIAL_FIGURE_T_PK PRIMARY KEY 
  (
    FIGURE_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_NEWSPAPER_SETUP_T 
(
  SETUP_ID NUMBER(2, 0) NOT NULL 
, NEWSPAPER_CATEGORY_ID VARCHAR2(80) 
, NEWSPAPER_TYPE VARCHAR2(40) 
, PAPER_TYPE VARCHAR2(40) 
, CHIEF_EDITOR VARCHAR2(80) 
, PRICE NUMBER(2, 0) 
, BOOK_SIZE VARCHAR2(40) 
, CN VARCHAR2(40) 
, ISSN VARCHAR2(40) 
, WORDS VARCHAR2(20) 
, PROD_SIZE VARCHAR2(40) 
, COMP_CODE VARCHAR2(40) 
, READER_GROUP VARCHAR2(40) 
, ORG VARCHAR2(80) 
, PUBLISHING VARCHAR2(80) 
, DESCRIPTION VARCHAR2(480) 
, DATENUM1 NUMBER 
, DATENUM2 NUMBER 
, DATENUM3 NUMBER 
, DATENUM4 NUMBER 
, DATENUM5 NUMBER 
, DATENUM6 NUMBER 
, DATENUM7 NUMBER 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, TOTAL NUMBER 
, LANG VARCHAR2(40) 
, CONSTRAINT CMS_NEWSPAPER_SETUP_T_PK PRIMARY KEY 
  (
    SETUP_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_NEWSPAPER_T 
(
  NEWSPAPER_ID NUMBER NOT NULL 
, NEWSPAPER_CATEGORY_ID NUMBER 
, NEWS_ID NUMBER 
, EDITOR VARCHAR2(80) 
, FORMAT_DESIGN VARCHAR2(80) 
, COVER_DESIGN VARCHAR2(80) 
, PUB_TIME DATE 
, KEYWORD VARCHAR2(4000) 
, PROD_SIZE VARCHAR2(40) 
, COLOR_NUM VARCHAR2(40) 
, COVER_TYPESET VARCHAR2(40) 
, ASSORT_PROD VARCHAR2(40) 
, BOOK_SIZE VARCHAR2(40) 
, MAIN_TYPESET VARCHAR2(40) 
, MAIN_PAGE VARCHAR2(40) 
, PAGINATION NUMBER 
, SUGGESTION VARCHAR2(4000) 
, REMARKS VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, DOC_ID NUMBER 
, TYPESET_COMP VARCHAR2(240) 
, CONSTRAINT CMS_NEWSPAPER_T_PK PRIMARY KEY 
  (
    NEWSPAPER_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_NEWS_SETUP_T 
(
  SETUP_ID NUMBER NOT NULL 
, NEWSPAPER_CATEGORY_ID NUMBER NOT NULL 
, YEAR NUMBER 
, NEWS_NUM NUMBER 
, PUBLIC_DATE DATE 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_NEWS_SETUP_T_PK PRIMARY KEY 
  (
    SETUP_ID 
  , NEWSPAPER_CATEGORY_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_PERIODICAL_SETUP_T 
(
  SETUP_ID DECIMAL(2) NOT NULL 
, PERIODICAL_CATEGORY_ID VARCHAR2(80) 
, PERIODICAL_TYPE VARCHAR2(40) 
, PAPER_TYPE VARCHAR2(40) 
, CHIEF_EDITOR VARCHAR2(80) 
, PRICE NUMBER(2) 
, BOOK_SIZE VARCHAR2(40) 
, CN VARCHAR2(40) 
, ISSN VARCHAR2(40) 
, WORDS VARCHAR2(20) 
, PROD_SIZE VARCHAR2(40) 
, COMP_CODE VARCHAR2(40) 
, READER_GROUP VARCHAR2(40) 
, ORG VARCHAR2(80) 
, PUBLISHING VARCHAR2(80) 
, DESCRIPTION VARCHAR2(480) 
, DATENUM1 NUMBER 
, DATENUM2 NUMBER 
, DATENUM3 NUMBER 
, DATENUM4 NUMBER 
, DATENUM5 NUMBER 
, DATENUM6 NUMBER 
, DATENUM7 NUMBER 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, TOTAL NUMBER 
, LANG VARCHAR2(40) 
, CONSTRAINT CMS_PERIODICAL_SETUP_T_PK PRIMARY KEY 
  (
    SETUP_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_PERIODICAL_T 
(
  PERIODICAL_ID NUMBER NOT NULL 
, PERIODICAL_CATEGORY_ID NUMBER 
, PERIOD_ID NUMBER 
, EDITOR VARCHAR2(80) 
, FORMAT_DESIGN VARCHAR2(80) 
, COVER_DESIGN VARCHAR2(80) 
, PUB_TIME DATE 
, KEYWORD VARCHAR2(4000) 
, PROD_SIZE VARCHAR2(40) 
, COLOR_NUM VARCHAR2(40) 
, COVER_TYPESET VARCHAR2(40) 
, ASSORT_PROD VARCHAR2(40) 
, BOOK_SIZE VARCHAR2(40) 
, MAIN_TYPESET VARCHAR2(40) 
, MAIN_PAGE VARCHAR2(40) 
, PAGINATION NUMBER 
, SUGGESTION VARCHAR2(4000) 
, REMARKS VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, DOC_ID NUMBER 
, TYPESET_COMP VARCHAR2(240) 
, CONSTRAINT CMS_PERIODICAL_T_PK PRIMARY KEY 
  (
    PERIODICAL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_PERIOD_SETUP_T 
(
  SETUP_ID NUMBER NOT NULL 
, PERIODICAL_CATEGORY_ID NUMBER NOT NULL 
, YEAR VARCHAR2(40) 
, PERIOD_NUM NUMBER 
, PUBLIC_DATE DATE 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_PERIOD_SETUP_T_PK PRIMARY KEY 
  (
    SETUP_ID 
  , PERIODICAL_CATEGORY_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_PHOTOGRAPHY_FIGURE_T 
(
  FIGURE_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, FIGURE_NAME VARCHAR2(80) 
, FIGURE_FORMAT VARCHAR2(20) 
, FIGURE_SIZE VARCHAR2(20) 
, FIGURE_DIMENSION VARCHAR2(20) 
, FIGURE_RESOLUTION VARCHAR2(80) 
, FIGURE_X_RESOLUTION VARCHAR2(80) 
, FIGURE_Y_RESOLUTION VARCHAR2(80) 
, COVER_DESIGN VARCHAR2(80) 
, SERIES_NAME VARCHAR2(80) 
, PHOTOGRAPHER VARCHAR2(80) 
, PHOTOGRAPHY_TYPE VARCHAR2(40) 
, PHOTOGRAPHY_TIME DATE 
, PHOTOGRAPHY_LOCATION VARCHAR2(80) 
, COMP_CODE VARCHAR2(20) 
, KEYWORD VARCHAR2(1000) 
, FIGURE_DESC VARCHAR2(4000) 
, REMARKS VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, FIGURE_WIDTH VARCHAR2(20) 
, FIGURE_HEIGHT VARCHAR2(20) 
, CONSTRAINT CMS_PHOTOGRAPHY_FIGURE_T_PK PRIMARY KEY 
  (
    FIGURE_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_PROCESS_LOG_T 
(
  LOG_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, OPERATION VARCHAR2(80) 
, PROCESS_OPERATOR VARCHAR2(40) 
, PROCESS_START_POINT VARCHAR2(80) 
, PROCESS_END_POINT VARCHAR2(80) 
, OPERATION_TIME DATE 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_PROCESS_LOG_T_PK PRIMARY KEY 
  (
    LOG_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_RES_EXP_APPLY_H_T 
(
  APPLY_ID NUMBER NOT NULL 
, APPLY_NAME VARCHAR2(80) 
, TEMPLATE_ID NUMBER 
, USER_ID NUMBER 
, COMP_CODE VARCHAR2(40) 
, BATCH_CODE VARCHAR2(20) 
, STATUS VARCHAR2(40) 
, REMARKS VARCHAR2(720) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_RES_EXP_APPLY_H_T_PK PRIMARY KEY 
  (
    APPLY_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_RES_EXP_APPLY_L_T 
(
  LINE_ID NUMBER NOT NULL 
, HEAD_ID NUMBER 
, SHELF_ID NUMBER 
, BATCH_CODE VARCHAR2(20) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_RES_EXP_APPLY_L_T_PK PRIMARY KEY 
  (
    LINE_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_RES_TEMPLATE_REL_T 
(
  REL_ID NUMBER NOT NULL 
, TEMPLATE_ID NUMBER 
, RES_CODE VARCHAR2(40) 
, RES_TYPE_CODE VARCHAR2(40) 
, BATCH_CODE VARCHAR2(20) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_RES_TEMPLATE_REL_T_PK PRIMARY KEY 
  (
    REL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_RES_TEMPLATE_T 
(
  TEMPLATE_ID NUMBER NOT NULL 
, TEMPLATE_NAME VARCHAR2(80) 
, USER_ID NUMBER 
, TEMP_FLAG VARCHAR2(10) 
, LAST_BATCH_CODE VARCHAR2(20) 
, DELETE_FLAG VARCHAR2(20) 
, CATEGORY_CODE VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_RES_TEMPLATE_T_PK PRIMARY KEY 
  (
    TEMPLATE_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_RES_TEMP_SHELF_T 
(
  SHELF_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, USER_ID NUMBER 
, DELETE_FLAG VARCHAR2(10) 
, APPLY_SUBMIT_FLAG VARCHAR2(10) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_TEMP_SHELF_T_PK PRIMARY KEY 
  (
    SHELF_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_ROLE_LIB_REL_T 
(
  REL_ID NUMBER NOT NULL 
, ROLE_ID NUMBER 
, LIB_CODE VARCHAR2(40) 
, LIB_TYPE_CODE VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_ROLE_LIB_REL_T_PK PRIMARY KEY 
  (
    REL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_ROLE_RES_REL_T 
(
  REL_ID NUMBER NOT NULL 
, ROLE_ID NUMBER 
, RES_CODE VARCHAR2(40) 
, RES_TYPE_CODE VARCHAR2(40) 
, AUTHORITY VARCHAR2(20) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_ROLE_RES_REL_T_PK PRIMARY KEY 
  (
    REL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_ROLE_T 
(
  ROLE_ID NUMBER NOT NULL 
, ROLE_NAME VARCHAR2(80) 
, ENABLE_FLAG VARCHAR2(10) 
, ROLE_TYPE VARCHAR2(20) 
, COMP_CODE VARCHAR2(40) 
, REMARKS VARCHAR2(240) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT PM_ROLE_T_PK PRIMARY KEY 
  (
    ROLE_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_ROLE_USER_REL_T 
(
  REL_ID NUMBER NOT NULL 
, ROLE_ID NUMBER 
, USER_ID NUMBER 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_ROLE_USER_REL_T_PK PRIMARY KEY 
  (
    REL_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_ROLLBACK_LOG_T 
(
  LOG_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, ROLLBACK_OPERATOR VARCHAR2(40) 
, OPERATION_TIME DATE 
, ROLLBACK_REASON VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_ROLLBACK_LOG_T_PK PRIMARY KEY 
  (
    LOG_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_SERVER_CONFIG_T 
(
  CONFIG_ID NUMBER NOT NULL 
, HOST VARCHAR2(80) 
, PORT NUMBER 
, ADMIN_USERNAME VARCHAR2(40) 
, ADMIN_PASSWORD VARCHAR2(40) 
, SERVER_TYPE VARCHAR2(20) 
, ENABLE_FLAG VARCHAR2(10) 
, VERSION NUMBER 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_SERVER_CONFIG_T_PK PRIMARY KEY 
  (
    CONFIG_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_TEACHING_PLAN_T 
(
  TEACHING_PLAN_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, SOURCE_BOOK_DOC_ID NUMBER 
, SOURCE_BOOK_NAME VARCHAR2(80) 
, SOURCE_BOOK_ISBN VARCHAR2(80) 
, PUBLISHING_HOUSE VARCHAR2(80) 
, SOURCE_BOOK_TYPE VARCHAR2(40) 
, COMP_CODE VARCHAR2(20) 
, EDITOR VARCHAR2(80) 
, TEACHING_PLAN_NAME VARCHAR2(80) 
, PRODUCER VARCHAR2(80) 
, TEACHING_PLAN_TYPE VARCHAR2(40) 
, COPYRIGHT_FLAG VARCHAR2(20) 
, KEYWORD VARCHAR2(1000) 
, REMARKS VARCHAR2(4000) 
, TEACHING_PLAN_STORE_TIME DATE 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_TEACHING_PLAN_T_PK PRIMARY KEY 
  (
    TEACHING_PLAN_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_THEME_T 
(
  THEME_ID NUMBER NOT NULL 
, THEME_NAME VARCHAR2(100) 
, THEME_DESC VARCHAR2(4000) 
, BINDING_THEME_ID NUMBER 
, BINDING_THEME_NAME VARCHAR2(100) 
, STATUS VARCHAR2(80) 
, COMP_CODE VARCHAR2(40) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_THEME_T_PK PRIMARY KEY 
  (
    THEME_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_USER_T 
(
  USER_ID NUMBER NOT NULL 
, USER_NAME VARCHAR2(40) 
, PASSWORD VARCHAR2(80) 
, DIPLAY_NAME VARCHAR2(80) 
, COMP_CODE VARCHAR2(40) 
, ENABLE_FLAG VARCHAR2(10) 
, REMARKS VARCHAR2(240) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_USER_T_PK PRIMARY KEY 
  (
    USER_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_VIDEO_T 
(
  VIDEO_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, FILE_NAME VARCHAR2(240) 
, FILE_FORMAT VARCHAR2(20) 
, FILE_SIZE VARCHAR2(20) 
, FILE_TIME VARCHAR2(20) 
, FILE_STORE_TIME DATE 
, SERIES_NAME VARCHAR2(240) 
, ISBN VARCHAR2(80) 
, ITEM_CODE VARCHAR2(40) 
, VIDEO_TYPE VARCHAR2(40) 
, CARRIER_TYPE VARCHAR2(40) 
, LANG VARCHAR2(20) 
, EDITOR VARCHAR2(80) 
, TEXT_EDITOR VARCHAR2(80) 
, PRODUCER VARCHAR2(80) 
, PUB_TIME DATE 
, ASSORT_BOOK VARCHAR2(80) 
, COMP_CODE VARCHAR2(20) 
, KEYWORD VARCHAR2(1000) 
, CONTENT_DESC VARCHAR2(4000) 
, REMARKS VARCHAR2(4000) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, PREVIEW_URL VARCHAR2(480) 
, SCRIPT CLOB 
, CONSTRAINT CMS_VIDEO_T_PK PRIMARY KEY 
  (
    VIDEO_ID 
  )
  ENABLE 
);

CREATE TABLE CMS_XC_INFO_T 
(
  XC_INFO_ID NUMBER NOT NULL 
, DOC_ID NUMBER 
, TITLE VARCHAR2(500) 
, AUTHOR VARCHAR2(100) 
, CONTENT CLOB 
, TYPE VARCHAR2(20) 
, OBJECT_VERSION_NUMBER NUMBER 
, CREATED_BY NUMBER 
, CREATION_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, LAST_UPDATE_DATE DATE 
, ATTRIBUTE1 VARCHAR2(240) 
, ATTRIBUTE2 VARCHAR2(240) 
, ATTRIBUTE3 VARCHAR2(240) 
, ATTRIBUTE4 VARCHAR2(240) 
, ATTRIBUTE5 VARCHAR2(240) 
, ATTRIBUTE6 VARCHAR2(240) 
, ATTRIBUTE7 VARCHAR2(240) 
, ATTRIBUTE8 VARCHAR2(240) 
, ATTRIBUTE9 VARCHAR2(240) 
, ATTRIBUTE10 VARCHAR2(240) 
, ATTRIBUTE11 VARCHAR2(240) 
, ATTRIBUTE12 VARCHAR2(240) 
, ATTRIBUTE13 VARCHAR2(240) 
, ATTRIBUTE14 VARCHAR2(240) 
, ATTRIBUTE15 VARCHAR2(240) 
, CONSTRAINT CMS_XC_INFO_T_PK PRIMARY KEY 
  (
    XC_INFO_ID 
  )
  ENABLE 
);

ALTER TABLE CMS_BOOK_T
ADD CONSTRAINT CMS_BOOK_T_UK1 UNIQUE 
(
  DOC_ID 
)
ENABLE;

ALTER TABLE CMS_CATEGORY_T
ADD CONSTRAINT CMS_CATEGORY_T_UK1 UNIQUE 
(
  CATEGORY_NAME 
, PARENT_NODE_TYPE 
, PARENT_NODE_ID 
)
ENABLE;

ALTER TABLE CMS_COMP_LIB_REL_T
ADD CONSTRAINT CMS_COMP_LIB_REL_T_UK1 UNIQUE 
(
  COMP_CODE 
, LIB_CODE 
, LIB_TYPE_CODE 
)
ENABLE;

ALTER TABLE CMS_DOC_CATEGORY_REL_T
ADD CONSTRAINT CMS_DOC_CATEGORY_REL_T_UK1 UNIQUE 
(
  DOC_ID 
, CATEGORY_ID 
)
ENABLE;

ALTER TABLE CMS_DOC_REL_T
ADD CONSTRAINT CMS_DOC_REL_T_UK1 UNIQUE 
(
  DOC_ID 
, PARENT_DOC_ID 
, REL_TYPE 
)
ENABLE;

ALTER TABLE CMS_DOC_UCM_REL_T
ADD CONSTRAINT CMS_DOC_UCM_REL_T_UK1 UNIQUE 
(
  DOC_ID 
, UCM_DOCNAME 
)
ENABLE;

ALTER TABLE CMS_LIB_CATEGORY_G_REL_T
ADD CONSTRAINT CMS_CATEGORY_GROUP_T_UK1 UNIQUE 
(
  CATEGORY_GROUP_CODE 
, LIB_CODE 
, LIB_TYPE_CODE 
, COMP_CODE 
)
ENABLE;

ALTER TABLE CMS_LIB_RES_REL_T
ADD CONSTRAINT CMS_LIB_RES_REL_T_UK1 UNIQUE 
(
  LIB_CODE 
, RES_CODE 
, RES_TYPE_CODE 
)
ENABLE;

ALTER TABLE CMS_ROLE_LIB_REL_T
ADD CONSTRAINT CMS_ROLE_LIB_REL_T_UK1 UNIQUE 
(
  ROLE_ID 
, LIB_CODE 
, LIB_TYPE_CODE 
)
ENABLE;

ALTER TABLE CMS_ROLE_RES_REL_T
ADD CONSTRAINT CMS_ROLE_RES_REL_T_UK1 UNIQUE 
(
  ROLE_ID 
, RES_CODE 
, RES_TYPE_CODE 
)
ENABLE;

ALTER TABLE CMS_ROLE_T
ADD CONSTRAINT PM_ROLE_T_UK1 UNIQUE 
(
  ROLE_TYPE 
, ROLE_NAME 
, COMP_CODE 
)
ENABLE;

ALTER TABLE CMS_ROLE_USER_REL_T
ADD CONSTRAINT CMS_ROLE_USER_REL_T_UK1 UNIQUE 
(
  ROLE_ID 
, USER_ID 
)
ENABLE;

ALTER TABLE CMS_SERVER_CONFIG_T
ADD CONSTRAINT CMS_SERVER_CONFIG_T_UK1 UNIQUE 
(
  HOST 
, PORT 
, SERVER_TYPE 
, ENABLE_FLAG 
, VERSION 
)
ENABLE;

ALTER TABLE CMS_USER_T
ADD CONSTRAINT CMS_USER_T_UK1 UNIQUE 
(
  USER_NAME 
)
ENABLE;

COMMENT ON TABLE CMS_ACTIVITY_T IS '活动库信息';

COMMENT ON TABLE CMS_ELEC_PROD_T IS '电子音像产品表';

COMMENT ON TABLE CMS_MATERIAL_FIGURE_T IS '素材图库';

COMMENT ON TABLE CMS_PROCESS_LOG_T IS '流程日志记录';

COMMENT ON TABLE CMS_ROLLBACK_LOG_T IS '回退日志记录';

COMMENT ON TABLE CMS_TEACHING_PLAN_T IS '教案库';

COMMENT ON TABLE CMS_VIDEO_T IS '视频库';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ITEMS_T.ITEM_ID IS '订单ID';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ITEMS_T.SALES_COST IS '销售总费用';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ITEMS_T.SALES_NUM IS '销售总数量';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ITEM_T.ORDER_ID IS '订单ID';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ITEM_T.SALES_TOTAL_COST IS '销售总费用';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ITEM_T.SALES_TOTAL_NUM IS '销售总数量';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ITEM_T.COMP_CODE IS '部门分类/分社';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ORDER_T.ORDER_ID IS '授权单ID，主键';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ORDER_T.ORDER_NAME IS '订单名称';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ORDER_T.AUTHORIZED_COMPANY IS '授权单位';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ORDER_T.AUTHORIZED_TYPE IS '授权类型';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ORDER_T.AUTHORIZED_FILE_TYPE IS '授权文件类型';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ORDER_T.AUTHORIZED_START_TIME IS '授权开始时间';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ORDER_T.AUTHORIZED_VALID_PERIOD IS '授权有效期';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ORDER_T.AUTHORIZED_LANG IS '授权语种';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ORDER_T.AUTHORIZED_AREA IS '授权地区';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ORDER_T.INCLUDE_PUBLIC_COPYRIGHT_FLAG IS '是否包括公众版标识';

COMMENT ON COLUMN CMS_3RD_AUTHORIZATION_ORDER_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_ACTIVITY_T.ACTIVITY_ID IS '活动Id，主键';

COMMENT ON COLUMN CMS_ACTIVITY_T.DOC_ID IS '文档id';

COMMENT ON COLUMN CMS_ACTIVITY_T.ACTIVITY_THEME IS '活动主题';

COMMENT ON COLUMN CMS_ACTIVITY_T.ACTIVITY_START_TIME IS '活动开始时间';

COMMENT ON COLUMN CMS_ACTIVITY_T.ACTIVITY_END_TIME IS '活动结束时间';

COMMENT ON COLUMN CMS_ACTIVITY_T.ACTIVITY_LOCATION IS '活动地点';

COMMENT ON COLUMN CMS_ACTIVITY_T.ACTIVITY_TYPE IS '活动分类';

COMMENT ON COLUMN CMS_ACTIVITY_T.COMP_CODE IS '部门分类/分社';

COMMENT ON COLUMN CMS_ACTIVITY_T.ACTIVITY_STORE_TIME IS '入库日期';

COMMENT ON COLUMN CMS_ACTIVITY_T.ACTIVITY_DESC IS '活动简介';

COMMENT ON COLUMN CMS_ACTIVITY_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_ATTACH_T.ATTACH_ID IS '附件ID，主键。';

COMMENT ON COLUMN CMS_ATTACH_T.DOC_ID IS '内容ID。';

COMMENT ON COLUMN CMS_ATTACH_T.SOURCE_ID IS '源Id';

COMMENT ON COLUMN CMS_ATTACH_T.PATH IS '路径';

COMMENT ON COLUMN CMS_ATTACH_T.TITLE IS '标题';

COMMENT ON COLUMN CMS_ATTACH_T.ATTACH_TYPE IS '附件类型';

COMMENT ON COLUMN CMS_ATTACH_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_ATTACH_T.FORMAT IS '格式';

COMMENT ON COLUMN CMS_ATTACH_T.FILE_SIZE IS '大小';

COMMENT ON COLUMN CMS_AUDIO_T.FILE_NAME IS '文件名称';

COMMENT ON COLUMN CMS_AUDIO_T.SERIES_NAME IS '系列名称';

COMMENT ON COLUMN CMS_AUDIO_T.ITEM_CODE IS '物料号';

COMMENT ON COLUMN CMS_AUDIO_T.AUDIO_TYPE IS '音频分类';

COMMENT ON COLUMN CMS_AUDIO_T.CARRIER_TYPE IS '载体类型';

COMMENT ON COLUMN CMS_AUDIO_T.LANG IS '语种';

COMMENT ON COLUMN CMS_AUDIO_T.EDITOR IS '责任编辑';

COMMENT ON COLUMN CMS_AUDIO_T.TEXT_EDITOR IS '文字编辑';

COMMENT ON COLUMN CMS_AUDIO_T.RECORD_USER IS '录音人员';

COMMENT ON COLUMN CMS_AUDIO_T.PUB_TIME IS '出版时间';

COMMENT ON COLUMN CMS_AUDIO_T.ASSORT_BOOK IS '配套图书';

COMMENT ON COLUMN CMS_AUDIO_T.DEPT_CODE IS '部分 分社';

COMMENT ON COLUMN CMS_AUDIO_T.KEYWORD IS '关键字';

COMMENT ON COLUMN CMS_AUDIO_T.CONTENT_DESC IS '内容简介';

COMMENT ON COLUMN CMS_AUDIO_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_AUDIO_T.FILE_FORMAT IS '文件格式';

COMMENT ON COLUMN CMS_AUDIO_T.FILE_SIZE IS '文件大小';

COMMENT ON COLUMN CMS_AUDIO_T.FILE_TIME IS '文件时长';

COMMENT ON COLUMN CMS_AUDIO_T.FILE_STORE_TIME IS '入库时间';

COMMENT ON COLUMN CMS_AUDIO_T.PREVIEW_URL IS '预览URL。';

COMMENT ON COLUMN CMS_AUDIO_T.SCRIPT IS '台本';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.COPYRIGHT_ID IS '作者版权信息ID，主键';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.DOC_ID IS '文档ID';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.BOOK_DOC_ID IS '图书的DOCID';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.COPYRIGHT_FORM IS '版权形式';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.EXCLUSIVE_COPYRIGHT_FLAG IS '独有版权标识';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.PART_PROBATION_FLAG IS '部分试读标识';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.PUBLIC_COPYRIGHT_FLAG IS '公众版标识';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.COPYRIGHT_OWNER IS '著作权人';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.COPYRIGHT_AGENT IS '版权代理人';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.AUTHORIZED_AREA IS '授权地区';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.AUTHORIZED_LANG IS '授权语种';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.COPYRIGHT_REGISTRATION_NUMBER IS '版权登记号';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.OVERSEAS_COPYRIGHT_FLAG IS '海外版权标识';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.OVERSEAS_ROYALTY IS '海外版税';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.DIGITAL_ROYALTY IS '数字版税';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.PAPER_MEDIUM_COPYRIGHT_FLAG IS '纸介质版权标识';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.PAPER_MEDIUM_START_TIME IS '纸介质版权开始时间';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.PAPER_MEDIUM_END_TIME IS '纸介质版权结束时间';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.ELECTRONIC_COPYRIGHT_FLAG IS '电子出版权标识';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.ELECTRONIC_START_TIME IS '电子出版权开始时间';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.ELECTRONIC_END_TIME IS '电子出版权结束时间';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.AUDIO_VIDEO_COPYRIGHT_FLAG IS '音像出版权标识';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.AUDIO_VIDEO_START_TIME IS '音像出版权开始时间';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.AUDIO_VIDEO_END_TIME IS '音像出版权结束时间';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.NETWORK_COPYRIGHT_FLAG IS '网络出版权标识';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.NETWORK_START_TIME IS '网络出版权开始时间';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.NETWORK_END_TIME IS '网络出版权结束时间';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.BROADCAST_COPYRIGHT_FLAG IS '广播出版权标识';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.BROADCAST_START_TIME IS '广播出版权开始时间';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.BROADCAST_END_TIME IS '广播出版权结束时间';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.COPYRIGHT_CIP IS '版权CIP';

COMMENT ON COLUMN CMS_AUTHOR_COPYRIGHT_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_BOOK_T.BOOK_ID IS '图书ID，主键。';

COMMENT ON COLUMN CMS_BOOK_T.DOC_ID IS '内容ID。';

COMMENT ON COLUMN CMS_BOOK_T.BOOK_NAME IS '书名。';

COMMENT ON COLUMN CMS_BOOK_T.ISBN IS 'ISBN。';

COMMENT ON COLUMN CMS_BOOK_T.SERIES IS '丛书名。';

COMMENT ON COLUMN CMS_BOOK_T.ITEM_CODE IS '物料号。';

COMMENT ON COLUMN CMS_BOOK_T.LANG IS '语种。';

COMMENT ON COLUMN CMS_BOOK_T.EDITOR IS '责任编辑。';

COMMENT ON COLUMN CMS_BOOK_T.FORMAT_DESIGN IS '版面设计。';

COMMENT ON COLUMN CMS_BOOK_T.COVER_DESIGN IS '封面设计。';

COMMENT ON COLUMN CMS_BOOK_T.AUTHOR IS '作者。';

COMMENT ON COLUMN CMS_BOOK_T.CHIEF_EDITOR IS '主编。';

COMMENT ON COLUMN CMS_BOOK_T.TRANSLATOR IS '译者。';

COMMENT ON COLUMN CMS_BOOK_T.PUB_TIME IS '出版时间。';

COMMENT ON COLUMN CMS_BOOK_T.PUBLISHING_HOUSE IS '出版社';

COMMENT ON COLUMN CMS_BOOK_T.IMPRESSION IS '印次。';

COMMENT ON COLUMN CMS_BOOK_T.EDITION IS '版次。';

COMMENT ON COLUMN CMS_BOOK_T.PAGINATION IS '页数。';

COMMENT ON COLUMN CMS_BOOK_T.PRICE IS '定价。';

COMMENT ON COLUMN CMS_BOOK_T.KEYWORD IS '关键字。';

COMMENT ON COLUMN CMS_BOOK_T.READER_GROUP IS '读者对象。';

COMMENT ON COLUMN CMS_BOOK_T.SUGGESTION IS '上架建议。';

COMMENT ON COLUMN CMS_BOOK_T.PROD_SIZE IS '成品尺寸。';

COMMENT ON COLUMN CMS_BOOK_T.COLOR_NUM IS '正文色数。';

COMMENT ON COLUMN CMS_BOOK_T.COVER_TYPESET IS '封面排版软件。';

COMMENT ON COLUMN CMS_BOOK_T.ASSORT_PROD IS '配套产品。';

COMMENT ON COLUMN CMS_BOOK_T.REMARKS IS '备注。';

COMMENT ON COLUMN CMS_BOOK_T.BOOK_SIZE IS '开本。';

COMMENT ON COLUMN CMS_BOOK_T.MAIN_PAGE IS '正文用纸。';

COMMENT ON COLUMN CMS_BOOK_T.MAIN_TYPESET IS '正文排版软件。';

COMMENT ON COLUMN CMS_BOOK_T.FORMAT_COMP IS '排版公司';

COMMENT ON COLUMN CMS_CATEGORY_T.CATEGORY_ID IS '分类ID，主键。';

COMMENT ON COLUMN CMS_CATEGORY_T.CATEGORY_NAME IS '类别名称。';

COMMENT ON COLUMN CMS_CATEGORY_T.PARENT_NODE_TYPE IS '父节点类型，CATEGORY_GROUP：类别组，CATEGORY：类别。';

COMMENT ON COLUMN CMS_CATEGORY_T.PARENT_NODE_ID IS '父节点ID。';

COMMENT ON COLUMN CMS_CATEGORY_T.SEQ IS '顺序。';

COMMENT ON COLUMN CMS_CHAPTER_T.CHAPTER_ID IS '章节ID，主键。';

COMMENT ON COLUMN CMS_CHAPTER_T.DOC_ID IS '所属DocId。';

COMMENT ON COLUMN CMS_CHAPTER_T.CHAPTER_CODE IS '章节代码。';

COMMENT ON COLUMN CMS_CHAPTER_T.CHAPTER_NAME IS '章节名。';

COMMENT ON COLUMN CMS_CHAPTER_T.CONTENT IS '章节内容。';

COMMENT ON COLUMN CMS_CHAPTER_T.SEQ IS '顺序。';

COMMENT ON COLUMN CMS_COMPANY_COPYRIGHT_T.COMPANY_ID IS '图书ID，主键。';

COMMENT ON COLUMN CMS_COMPANY_COPYRIGHT_T.COMPANY_NAME IS '书名。';

COMMENT ON COLUMN CMS_COMPANY_COPYRIGHT_T.COMPANY_ADDR IS 'ISBN。';

COMMENT ON COLUMN CMS_COMPANY_COPYRIGHT_T.COMPANY_CONTACT IS '丛书名。';

COMMENT ON COLUMN CMS_COMPANY_COPYRIGHT_T.COMPANY_PHONE IS '物料号。';

COMMENT ON COLUMN CMS_COMPANY_COPYRIGHT_T.REMARKS IS '版面设计。';

COMMENT ON COLUMN CMS_COMP_LIB_REL_T.REL_ID IS '关系ID，主键。';

COMMENT ON COLUMN CMS_COMP_LIB_REL_T.COMP_CODE IS '出版社代码。';

COMMENT ON COLUMN CMS_COMP_LIB_REL_T.LIB_CODE IS '库代码。';

COMMENT ON COLUMN CMS_COMP_LIB_REL_T.LIB_TYPE_CODE IS '库类型代码。';

COMMENT ON COLUMN CMS_COURSEWARE_T.COURSEWARE_ID IS '课件id,主键';

COMMENT ON COLUMN CMS_COURSEWARE_T.DOC_ID IS '文档id
';

COMMENT ON COLUMN CMS_COURSEWARE_T.TEACHING_MATERIAL_NAME IS '所属教材名';

COMMENT ON COLUMN CMS_COURSEWARE_T.TEACHING_MATERIAL_ISBN IS '所属教材isbn';

COMMENT ON COLUMN CMS_COURSEWARE_T.TEACHING_MATERIAL_AUTHOR IS '所属教材作者';

COMMENT ON COLUMN CMS_COURSEWARE_T.TEACHING_MATERIAL_EDITOR IS '所属教材编辑';

COMMENT ON COLUMN CMS_COURSEWARE_T.TEACHING_MATERIAL_SERIES_NAME IS '所属教材丛书名';

COMMENT ON COLUMN CMS_COURSEWARE_T.TEACHING_MATERIAL_TYPE IS '所属教材分类';

COMMENT ON COLUMN CMS_COURSEWARE_T.COMP_CODE IS '所属部门';

COMMENT ON COLUMN CMS_COURSEWARE_T.COURSEWARE_TYPE IS '课件类型';

COMMENT ON COLUMN CMS_COURSEWARE_T.COURSEWARE_NAME IS '课件名称';

COMMENT ON COLUMN CMS_COURSEWARE_T.COPYRIGHT_FLAG IS '版权信息（有/无）';

COMMENT ON COLUMN CMS_COURSEWARE_T.KEYWORD IS '关键词';

COMMENT ON COLUMN CMS_COURSEWARE_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_COURSEWARE_T.UPLOAD_TIME IS '上传时间';

COMMENT ON COLUMN CMS_DOCBOOK_JOB_T.JOB_ID IS '任务ID，主键。';

COMMENT ON COLUMN CMS_DOCBOOK_JOB_T.JOB_NAME IS '任务名称。';

COMMENT ON COLUMN CMS_DOCBOOK_JOB_T.COMP_CODE IS '出版社代码。';

COMMENT ON COLUMN CMS_DOCBOOK_JOB_T.ISBN IS 'ISBN。';

COMMENT ON COLUMN CMS_DOCBOOK_JOB_T.STATUS IS '状态（待入库，入库中，已入库，已失败），来源于LOOKUP。';

COMMENT ON COLUMN CMS_DOCBOOK_JOB_T.RESULT IS '结果，来源与LOOKUP。';

COMMENT ON COLUMN CMS_DOCBOOK_MONITOR_T.MONITOR_ID IS '监控ID，主键。';

COMMENT ON COLUMN CMS_DOCBOOK_MONITOR_T.JOB_ID IS '任务ID。';

COMMENT ON COLUMN CMS_DOCBOOK_MONITOR_T.START_DATE IS '开始时间。';

COMMENT ON COLUMN CMS_DOCBOOK_MONITOR_T.END_DATE IS '结束时间。';

COMMENT ON COLUMN CMS_DOCBOOK_MONITOR_T.STATUS IS '状态，来源于LOOKUP。';

COMMENT ON COLUMN CMS_DOCBOOK_MONITOR_T.RESULT IS '结果，SUCCESS表示成功，FAIL表示失败。';

COMMENT ON COLUMN CMS_DOCBOOK_MONITOR_T.REMARKS IS '失败原因。';

COMMENT ON COLUMN CMS_DOC_CATEGORY_REL_T.REL_ID IS '关系ID，主键。';

COMMENT ON COLUMN CMS_DOC_CATEGORY_REL_T.DOC_ID IS '内容ID。';

COMMENT ON COLUMN CMS_DOC_CATEGORY_REL_T.CATEGORY_ID IS '分类ID。';

COMMENT ON COLUMN CMS_DOC_CATEGORY_REL_T.CATEGORY_GROUP_TYPE IS '分类组类型。';

COMMENT ON COLUMN CMS_DOC_GROUP_REL_T.REL_ID IS '主键';

COMMENT ON COLUMN CMS_DOC_GROUP_REL_T.DOC_ID IS 'DOCID';

COMMENT ON COLUMN CMS_DOC_GROUP_REL_T.GROUP_ID IS '组图ID';

COMMENT ON COLUMN CMS_DOC_GROUP_REL_T.INDEX_FLAG IS '索引标识（是否为索引图）';

COMMENT ON COLUMN CMS_DOC_REL_T.REL_ID IS '关系ID，主键。';

COMMENT ON COLUMN CMS_DOC_REL_T.DOC_ID IS '内容ID。';

COMMENT ON COLUMN CMS_DOC_REL_T.PARENT_DOC_ID IS '父内容ID。';

COMMENT ON COLUMN CMS_DOC_REL_T.REL_TYPE IS '关系类型，如封面，音频，视频等。';

COMMENT ON COLUMN CMS_DOC_T.DOC_ID IS '内容ID，主键。';

COMMENT ON COLUMN CMS_DOC_T.LIB_CODE IS '库代码。';

COMMENT ON COLUMN CMS_DOC_T.LIB_TYPE_CODE IS '库类型代码。';

COMMENT ON COLUMN CMS_DOC_T.COMP_CODE IS '出版社代码。';

COMMENT ON COLUMN CMS_DOC_T.STATUS IS '状态。';

COMMENT ON COLUMN CMS_DOC_T.SOURCE_STATUS IS '原状态，当文档状态变为待同步时，此字段存储状态更改之前的状态，以便后续恢复到原状态。';

COMMENT ON COLUMN CMS_DOC_T.THUMBNAIL_URL IS '缩略图URL';

COMMENT ON COLUMN CMS_DOC_T.DELETE_FLAG IS '删除标识，Y为已删除，N或空为未删除。';

COMMENT ON COLUMN CMS_DOC_T.CHAPTER_FLAG IS '是否存在章节。';

COMMENT ON COLUMN CMS_DOC_UCM_REL_T.REL_ID IS '关系ID，主键。';

COMMENT ON COLUMN CMS_DOC_UCM_REL_T.DOC_ID IS '内容ID。';

COMMENT ON COLUMN CMS_DOC_UCM_REL_T.UCM_DID IS 'UCM，dID。';

COMMENT ON COLUMN CMS_DOC_UCM_REL_T.UCM_DOCNAME IS 'UCM，dDocName。';

COMMENT ON COLUMN CMS_DOC_UCM_REL_T.FILE_NAME IS '文件名。';

COMMENT ON COLUMN CMS_DOC_UCM_REL_T.FTP_PATH IS 'FTP路径，如封面/高精度封面。';

COMMENT ON COLUMN CMS_DOC_UCM_REL_T.FTP_UPLOAD_DATE IS 'FTP上传时间。';

COMMENT ON COLUMN CMS_DOC_UCM_REL_T.HAS_THUMBNAIL_FLAG IS '是否有对应的缩略图。';

COMMENT ON COLUMN CMS_DOC_UCM_REL_T.REF_DOC_ID IS '参考的文档ID。';

COMMENT ON COLUMN CMS_DOC_UCM_REL_T.DOC_TYPE IS '文档类型。';

COMMENT ON COLUMN CMS_ELEC_PROD_T.ELEC_PROD_ID IS '电子音像产品ID，主键';

COMMENT ON COLUMN CMS_ELEC_PROD_T.DOC_ID IS '内容ID';

COMMENT ON COLUMN CMS_ELEC_PROD_T.ELEC_PROD_NAME IS '产品名称';

COMMENT ON COLUMN CMS_ELEC_PROD_T.ISBN IS 'ISRC/ISBN';

COMMENT ON COLUMN CMS_ELEC_PROD_T.ITEM_CODE IS '物料号';

COMMENT ON COLUMN CMS_ELEC_PROD_T.ASSORT_BOOK IS '配套图书';

COMMENT ON COLUMN CMS_ELEC_PROD_T.PROD_TYPE IS '产品分类';

COMMENT ON COLUMN CMS_ELEC_PROD_T.PUBLISHING_HOUSE IS '出版社';

COMMENT ON COLUMN CMS_ELEC_PROD_T.LANG IS '语种';

COMMENT ON COLUMN CMS_ELEC_PROD_T.CARRIER_TYPE IS '载体类型';

COMMENT ON COLUMN CMS_ELEC_PROD_T.TIME_LENGTH IS '时长';

COMMENT ON COLUMN CMS_ELEC_PROD_T.AMOUNT IS '盒/盘数';

COMMENT ON COLUMN CMS_ELEC_PROD_T.DISK_DESIGN IS '盘面设计';

COMMENT ON COLUMN CMS_ELEC_PROD_T.EDITOR IS '责任编辑';

COMMENT ON COLUMN CMS_ELEC_PROD_T.TEXT_EDITOR IS '文字编辑';

COMMENT ON COLUMN CMS_ELEC_PROD_T.PRODUCER IS '制作人';

COMMENT ON COLUMN CMS_ELEC_PROD_T.PUB_TIME IS '出版/制作时间';

COMMENT ON COLUMN CMS_ELEC_PROD_T.COMP_CODE IS '分社';

COMMENT ON COLUMN CMS_ELEC_PROD_T.KEYWORD IS '关键词';

COMMENT ON COLUMN CMS_ELEC_PROD_T.CONTENT_DESC IS '内容简介';

COMMENT ON COLUMN CMS_ELEC_PROD_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_ELEC_PROD_T.SCRIPT IS '台本';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.IMAGE_DESCRIPTION IS '图像描述';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.MAKE IS '相机生产商';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.MODEL IS '相机型号';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.ORIENTATION IS '方向';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.X_RESOLUTION IS '水平分辨率';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.Y_RESOLUTION IS '垂直分辨率';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.RESOLUTION_UNIT IS '分辨率单位';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.DATE_TIME IS '日期/时间';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.YCBCR_POSITIONING IS '色相定位';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.EXPOSURE_TIME IS '快门速度';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.F_NUMBER IS '光圈值';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.ISO_SPEED_RATINGS IS '感光度';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.EXIF_VERSION IS 'EXIF版本';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.DATE_TIME_ORIGINAL IS '原始拍摄时间';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.DATE_TIME_DIGITIZED IS '数字化时间';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.COMPONENTS_CONFIGURATION IS '图像构造';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.COMPRESSED_BITS_PER_PIXEL IS '压缩程度';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.SHUTTER_SPEED_VALUE IS '快门速度值';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.APERTURE_VALUE IS '光圈值';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.EXPOSURE_BIAS_VALUE IS '曝光补偿';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.MAX_APERTURE_VALUE IS '最大光圈值';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.METERING_MODE IS '测光方式';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.FLASH IS '闪光
';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.FOCAL_LENGTH IS '焦距';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.FLASHPIX_VERSION IS 'FlashPix版本';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.COLOR_SPACE IS '颜色空间';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.EXIF_IMAGE_WIDTH IS '图像宽度';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.EXIF_IMAGE_HEIGHT IS '图像高度';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.FOCAL_PLANE_X_RESOLUTION IS '焦平面水平分辨率';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.FOCAL_PLANE_Y_RESOLUTION IS '焦平面垂直分辨率';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.FOCAL_PLANE_RESOLUTION_UNIT IS '焦平面分辨率单位';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.SENSING_METHOD IS '传感方法';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.FILE_SOURCE IS '源文件';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.CUSTOM_RENDERED IS '自定义渲染';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.EXPOSURE_MODE IS '曝光模式';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.WHITE_BALANCE IS '白平衡';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.DIGITAL_ZOOM_RATIO IS '数字变焦比率';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.SCENE_CAPTURE_TYPE IS '现场捕获类型';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.COMPRESSION IS '压缩格式';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.THUMBNAIL_OFFSET IS '缩略图偏移';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.THUMBNAIL_LENGTH IS '缩略图长度';

COMMENT ON COLUMN CMS_FIGURE_EXIF_INFO_T.THUMBNAIL_DATA IS '缩略图数据';

COMMENT ON COLUMN CMS_FIGURE_GROUP_T.GROUP_ID IS '组图的组ID，主键';

COMMENT ON COLUMN CMS_FIGURE_GROUP_T.GROUP_NAME IS '组名';

COMMENT ON COLUMN CMS_FIGURE_GROUP_T.GROUP_DESC IS '组描述';

COMMENT ON COLUMN CMS_FIGURE_GROUP_T.LIB_CODE IS '库代码';

COMMENT ON COLUMN CMS_GATHER_MONITOR_T.MONITOR_ID IS '监控ID，主键。';

COMMENT ON COLUMN CMS_GATHER_MONITOR_T.DOC_ID IS 'CMS文档ID。';

COMMENT ON COLUMN CMS_GATHER_MONITOR_T.FILE_NAME IS '文件名。';

COMMENT ON COLUMN CMS_GATHER_MONITOR_T.FILE_PATH IS '文件路径。';

COMMENT ON COLUMN CMS_GATHER_MONITOR_T.RESULT IS '采集结果。';

COMMENT ON COLUMN CMS_GATHER_MONITOR_T.THUMBNAIL_RESULT IS '缩略图采集结果。';

COMMENT ON COLUMN CMS_GATHER_MONITOR_T.REMARKS IS '备注。';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.ILLUSTRATION_ID IS '插图ID，主键';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.DOC_ID IS '文档ID';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.ILLUSTRATION_NAME IS '插图名称';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.ILLUSTRATION_SOURCE IS '图片来源';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.ILLUSTRATION_TYPE IS '插图分类';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.ILLUSTRATION_AUTHOR IS '插图作者';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.MAP_APPROVE_NUM IS '地图审批号';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.PAGE_NUMBER IS '页码';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.KEYWORD IS '关键词';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.ILLUSTRATION_DESC IS '图片说明';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.FIGURE_FORMAT IS '图片格式';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.FIGURE_DIMENSION IS '图片尺寸';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.FIGURE_SIZE IS '图片大小';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.COVER_DESIGN IS '封面设计';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.FIGURE_RESOLUTION IS '图片分辨率';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.FIGURE_X_RESOLUTION IS '图片X分辨率';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.FIGURE_Y_RESOLUTION IS '图片Y分辨率';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.FIGURE_WIDTH IS '图片宽';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.FIGURE_HEIGHT IS '图片高';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.FIGURE_STORE_TIME IS '入库时间';

COMMENT ON COLUMN CMS_ILLUSTRATION_T.COPYRIGHT_FLAG IS '版权信息(有/无)';

COMMENT ON COLUMN CMS_JB_INFO_T.JB_INFO_ID IS '精编信息ID，主键';

COMMENT ON COLUMN CMS_JB_INFO_T.BRIEF_INTRODUCTION IS '简介';

COMMENT ON COLUMN CMS_JB_INFO_T.CATALOG IS '目录';

COMMENT ON COLUMN CMS_JB_INFO_T.FOREWORD IS '前言';

COMMENT ON COLUMN CMS_JB_INFO_T.POSTSCRIPT IS '后记';

COMMENT ON COLUMN CMS_JB_INFO_T.HIGHLIGHTS IS '精彩片段';

COMMENT ON COLUMN CMS_JB_INFO_T.PREFACE IS '序言';

COMMENT ON COLUMN CMS_JB_INFO_T.GLOSSARY IS '术语表';

COMMENT ON COLUMN CMS_JB_INFO_T.REFERENCES IS '参考文献';

COMMENT ON COLUMN CMS_JB_INFO_T.AUTHOR_INTRODUCTION IS '作者简介';

COMMENT ON COLUMN CMS_LIB_CATEGORY_G_REL_T.REL_ID IS '关系ID，主键。';

COMMENT ON COLUMN CMS_LIB_CATEGORY_G_REL_T.CATEGORY_GROUP_CODE IS '分类组代码。';

COMMENT ON COLUMN CMS_LIB_CATEGORY_G_REL_T.LIB_CODE IS '库代码。';

COMMENT ON COLUMN CMS_LIB_CATEGORY_G_REL_T.LIB_TYPE_CODE IS '库类型代码。';

COMMENT ON COLUMN CMS_LIB_CATEGORY_G_REL_T.COMP_CODE IS '出版社代码。';

COMMENT ON COLUMN CMS_LIB_CATEGORY_G_REL_T.PRIMARY_FLAG IS '是否为主分类。';

COMMENT ON COLUMN CMS_LIB_CATEGORY_G_REL_T.ENABLE_FLAG IS '是否有效。';

COMMENT ON COLUMN CMS_LIB_RES_REL_T.REL_ID IS '关系ID，主键。';

COMMENT ON COLUMN CMS_LIB_RES_REL_T.LIB_CODE IS '库代码。';

COMMENT ON COLUMN CMS_LIB_RES_REL_T.RES_CODE IS '操作代码。';

COMMENT ON COLUMN CMS_LIB_RES_REL_T.RES_TYPE_CODE IS '操作类型代码。';

COMMENT ON COLUMN CMS_LOOKUP_TYPE_T.LOOKUP_TYPE_ID IS '主键ID。';

COMMENT ON COLUMN CMS_LOOKUP_TYPE_T.LOOKUP_TYPE_CODE IS '类型代码。';

COMMENT ON COLUMN CMS_LOOKUP_TYPE_T.LOOKUP_TYPE_NAME IS '类型名称。';

COMMENT ON COLUMN CMS_LOOKUP_TYPE_T.LOOKUP_TYPE_DESC IS '类型描述。';

COMMENT ON COLUMN CMS_LOOKUP_TYPE_T.ENABLE_FLAG IS '是否有效。';

COMMENT ON COLUMN CMS_LOOKUP_TYPE_T.MODULE_TYPE IS '模块类型。';

COMMENT ON COLUMN CMS_LOOKUP_TYPE_T.MODULE_CODE IS '模块代码。';

COMMENT ON COLUMN CMS_LOOKUP_VALUE_T.LOOKUP_VALUE_ID IS '主键ID。';

COMMENT ON COLUMN CMS_LOOKUP_VALUE_T.LOOKUP_VALUE_CODE IS '值代码。';

COMMENT ON COLUMN CMS_LOOKUP_VALUE_T.LOOKUP_TYPE_CODE IS '类型代码。';

COMMENT ON COLUMN CMS_LOOKUP_VALUE_T.MEANING IS '含义。';

COMMENT ON COLUMN CMS_LOOKUP_VALUE_T.LOOKUP_VALUE_DESC IS '值描述。';

COMMENT ON COLUMN CMS_LOOKUP_VALUE_T.ENABLE_FLAG IS '是否有效。';

COMMENT ON COLUMN CMS_LOOKUP_VALUE_T.SEQ IS '顺序。';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_ID IS '素材图ID，主键';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.DOC_ID IS '文档Id';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_NAME IS '图片名称';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_FORMAT IS '图片格式';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_DIMENSION IS '图片尺寸';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_SIZE IS '图片大小';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.COVER_DESIGN IS '封面设计';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_RESOLUTION IS '图片分辨率';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_X_RESOLUTION IS '图片X分辨率';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_Y_RESOLUTION IS '图片Y分辨率';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_WIDTH IS '图片宽';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_HEIGHT IS '图片高';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_STORE_TIME IS '入库时间';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_CODE IS '图片代码';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.SERIES_NAME IS '系列名称';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_AUTHOR IS '图片作者';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_TYPE IS '图片分类';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_STYLE IS '图片风格';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.COMP_CODE IS '分社';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.KEYWORD IS '关键词';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.FIGURE_DESC IS '图片说明';

COMMENT ON COLUMN CMS_MATERIAL_FIGURE_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.SETUP_ID IS '设置ID，主键。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.NEWSPAPER_CATEGORY_ID IS '期刊ID，来源于分类表。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.PAPER_TYPE IS '用纸类型，来源于LOOKUP。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.CHIEF_EDITOR IS '主编。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.PRICE IS '定价。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.CN IS 'CN。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.ISSN IS 'ISSN。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.WORDS IS '版字数。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.PROD_SIZE IS '成品尺寸。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.COMP_CODE IS '出版社。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.ORG IS '主管单位。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.PUBLISHING IS '出版发行。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.DESCRIPTION IS '刊物描述。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.DATENUM1 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.DATENUM2 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.DATENUM3 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.DATENUM4 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.DATENUM5 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.DATENUM6 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_NEWSPAPER_SETUP_T.DATENUM7 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.NEWSPAPER_ID IS '期刊ID，主键。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.NEWSPAPER_CATEGORY_ID IS '期刊分类ID。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.NEWS_ID IS '刊期ID。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.EDITOR IS '责任编辑。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.FORMAT_DESIGN IS '版面设计。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.COVER_DESIGN IS '封面设计。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.PUB_TIME IS '出版时间。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.KEYWORD IS '关键字。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.PROD_SIZE IS '成品尺寸。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.COLOR_NUM IS '正文色数。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.COVER_TYPESET IS '封面排版软件。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.ASSORT_PROD IS '配套产品。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.BOOK_SIZE IS '开本。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.MAIN_TYPESET IS '正文排版软件。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.MAIN_PAGE IS '正文用纸。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.PAGINATION IS '页数。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.SUGGESTION IS '上架建议。';

COMMENT ON COLUMN CMS_NEWSPAPER_T.REMARKS IS '备注。';

COMMENT ON COLUMN CMS_NEWS_SETUP_T.SETUP_ID IS '设置ID，主键。';

COMMENT ON COLUMN CMS_NEWS_SETUP_T.NEWSPAPER_CATEGORY_ID IS '期刊分类ID。';

COMMENT ON COLUMN CMS_NEWS_SETUP_T.YEAR IS '年度';

COMMENT ON COLUMN CMS_NEWS_SETUP_T.NEWS_NUM IS '刊期。';

COMMENT ON COLUMN CMS_NEWS_SETUP_T.PUBLIC_DATE IS '出版日期。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.SETUP_ID IS '设置ID，主键。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.PERIODICAL_CATEGORY_ID IS '期刊ID，来源于分类表。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.PAPER_TYPE IS '用纸类型，来源于LOOKUP。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.CHIEF_EDITOR IS '主编。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.PRICE IS '定价。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.CN IS 'CN。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.ISSN IS 'ISSN。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.WORDS IS '版字数。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.PROD_SIZE IS '成品尺寸。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.COMP_CODE IS '出版社。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.ORG IS '主管单位。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.PUBLISHING IS '出版发行。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DESCRIPTION IS '刊物描述。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM1 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM2 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM3 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM4 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM5 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM6 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_SETUP_T.DATENUM7 IS '日期数，不同的PERIODICAL_TYPE存储的内容也不同。';

COMMENT ON COLUMN CMS_PERIODICAL_T.PERIODICAL_ID IS '期刊ID，主键。';

COMMENT ON COLUMN CMS_PERIODICAL_T.PERIODICAL_CATEGORY_ID IS '期刊分类ID。';

COMMENT ON COLUMN CMS_PERIODICAL_T.PERIOD_ID IS '刊期ID。';

COMMENT ON COLUMN CMS_PERIODICAL_T.EDITOR IS '责任编辑。';

COMMENT ON COLUMN CMS_PERIODICAL_T.FORMAT_DESIGN IS '版面设计。';

COMMENT ON COLUMN CMS_PERIODICAL_T.COVER_DESIGN IS '封面设计。';

COMMENT ON COLUMN CMS_PERIODICAL_T.PUB_TIME IS '出版时间。';

COMMENT ON COLUMN CMS_PERIODICAL_T.KEYWORD IS '关键字。';

COMMENT ON COLUMN CMS_PERIODICAL_T.PROD_SIZE IS '成品尺寸。';

COMMENT ON COLUMN CMS_PERIODICAL_T.COLOR_NUM IS '正文色数。';

COMMENT ON COLUMN CMS_PERIODICAL_T.COVER_TYPESET IS '封面排版软件。';

COMMENT ON COLUMN CMS_PERIODICAL_T.ASSORT_PROD IS '配套产品。';

COMMENT ON COLUMN CMS_PERIODICAL_T.BOOK_SIZE IS '开本。';

COMMENT ON COLUMN CMS_PERIODICAL_T.MAIN_TYPESET IS '正文排版软件。';

COMMENT ON COLUMN CMS_PERIODICAL_T.MAIN_PAGE IS '正文用纸。';

COMMENT ON COLUMN CMS_PERIODICAL_T.PAGINATION IS '页数。';

COMMENT ON COLUMN CMS_PERIODICAL_T.SUGGESTION IS '上架建议。';

COMMENT ON COLUMN CMS_PERIODICAL_T.REMARKS IS '备注。';

COMMENT ON COLUMN CMS_PERIOD_SETUP_T.SETUP_ID IS '设置ID，主键。';

COMMENT ON COLUMN CMS_PERIOD_SETUP_T.PERIODICAL_CATEGORY_ID IS '期刊分类ID。';

COMMENT ON COLUMN CMS_PERIOD_SETUP_T.YEAR IS '年度';

COMMENT ON COLUMN CMS_PERIOD_SETUP_T.PERIOD_NUM IS '刊期。';

COMMENT ON COLUMN CMS_PERIOD_SETUP_T.PUBLIC_DATE IS '出版日期。';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.FIGURE_ID IS ' 摄影图ID，主键';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.DOC_ID IS '文档ID';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.FIGURE_NAME IS '图片名称';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.FIGURE_FORMAT IS '图片格式';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.FIGURE_SIZE IS '图片大小';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.FIGURE_DIMENSION IS '图片尺寸';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.FIGURE_RESOLUTION IS '图片分辨率';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.FIGURE_X_RESOLUTION IS '图片X分辨率';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.FIGURE_Y_RESOLUTION IS '图片Y分辨率';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.COVER_DESIGN IS '封面设计';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.SERIES_NAME IS '系列名称';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.PHOTOGRAPHER IS '摄影人';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.PHOTOGRAPHY_TYPE IS '摄影分类';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.PHOTOGRAPHY_LOCATION IS '摄影地点';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.COMP_CODE IS '分社';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.KEYWORD IS '关键词';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.FIGURE_DESC IS '图片说明';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.FIGURE_WIDTH IS '图片宽';

COMMENT ON COLUMN CMS_PHOTOGRAPHY_FIGURE_T.FIGURE_HEIGHT IS '图片高';

COMMENT ON COLUMN CMS_PROCESS_LOG_T.LOG_ID IS '流程日志ID，主键';

COMMENT ON COLUMN CMS_PROCESS_LOG_T.DOC_ID IS '关联的文档ID';

COMMENT ON COLUMN CMS_PROCESS_LOG_T.OPERATION IS '操作';

COMMENT ON COLUMN CMS_PROCESS_LOG_T.PROCESS_OPERATOR IS '操作人';

COMMENT ON COLUMN CMS_PROCESS_LOG_T.PROCESS_START_POINT IS '流程开始点';

COMMENT ON COLUMN CMS_PROCESS_LOG_T.PROCESS_END_POINT IS '流程结束点';

COMMENT ON COLUMN CMS_PROCESS_LOG_T.OPERATION_TIME IS '操作时间';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_H_T.APPLY_ID IS '资源导出申请ID，主键。';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_H_T.APPLY_NAME IS '资源导出申请名称。';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_H_T.TEMPLATE_ID IS '模板ID。';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_H_T.USER_ID IS '用户ID。';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_H_T.COMP_CODE IS '出版社代码。';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_H_T.BATCH_CODE IS '批代码。';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_H_T.STATUS IS '状态。';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_H_T.REMARKS IS '备注。';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_L_T.LINE_ID IS '行ID，主键。';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_L_T.HEAD_ID IS '头ID。';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_L_T.SHELF_ID IS '资源暂存架ID。';

COMMENT ON COLUMN CMS_RES_EXP_APPLY_L_T.BATCH_CODE IS '批代码。';

COMMENT ON COLUMN CMS_RES_TEMPLATE_REL_T.REL_ID IS '关系ID，主键。';

COMMENT ON COLUMN CMS_RES_TEMPLATE_REL_T.TEMPLATE_ID IS '模板ID。';

COMMENT ON COLUMN CMS_RES_TEMPLATE_REL_T.BATCH_CODE IS '批代码。';

COMMENT ON COLUMN CMS_RES_TEMPLATE_T.TEMPLATE_ID IS '模板ID，主键。';

COMMENT ON COLUMN CMS_RES_TEMPLATE_T.TEMPLATE_NAME IS '模板名。';

COMMENT ON COLUMN CMS_RES_TEMPLATE_T.USER_ID IS '用户ID。';

COMMENT ON COLUMN CMS_RES_TEMPLATE_T.TEMP_FLAG IS '是否为临时模板。';

COMMENT ON COLUMN CMS_RES_TEMPLATE_T.LAST_BATCH_CODE IS '最新批代码。';

COMMENT ON COLUMN CMS_RES_TEMPLATE_T.DELETE_FLAG IS '删除标识。';

COMMENT ON COLUMN CMS_RES_TEMPLATE_T.CATEGORY_CODE IS '库代码。';

COMMENT ON COLUMN CMS_RES_TEMP_SHELF_T.SHELF_ID IS '资源暂存架ID，主键。';

COMMENT ON COLUMN CMS_RES_TEMP_SHELF_T.DOC_ID IS '文档ID。';

COMMENT ON COLUMN CMS_RES_TEMP_SHELF_T.USER_ID IS '用户ID。';

COMMENT ON COLUMN CMS_RES_TEMP_SHELF_T.DELETE_FLAG IS '删除标识。';

COMMENT ON COLUMN CMS_RES_TEMP_SHELF_T.APPLY_SUBMIT_FLAG IS '导出申请提交标识。';

COMMENT ON COLUMN CMS_ROLE_LIB_REL_T.REL_ID IS '关系ID，主键。';

COMMENT ON COLUMN CMS_ROLE_LIB_REL_T.ROLE_ID IS '角色ID。';

COMMENT ON COLUMN CMS_ROLE_LIB_REL_T.LIB_CODE IS '库代码。';

COMMENT ON COLUMN CMS_ROLE_LIB_REL_T.LIB_TYPE_CODE IS '库类型代码。';

COMMENT ON COLUMN CMS_ROLE_RES_REL_T.REL_ID IS '关系ID，主键。';

COMMENT ON COLUMN CMS_ROLE_RES_REL_T.ROLE_ID IS '角色ID。';

COMMENT ON COLUMN CMS_ROLE_RES_REL_T.RES_CODE IS '资源代码。';

COMMENT ON COLUMN CMS_ROLE_RES_REL_T.RES_TYPE_CODE IS '资源类型代码。';

COMMENT ON COLUMN CMS_ROLE_RES_REL_T.AUTHORITY IS '工作平台角色 0：不权限；1：有权限。
发布平台角色 0：不下载；1：审批下载；2：自由下载。';

COMMENT ON COLUMN CMS_ROLE_T.ROLE_ID IS '角色ID，主键。';

COMMENT ON COLUMN CMS_ROLE_T.ROLE_NAME IS '角色名称。';

COMMENT ON COLUMN CMS_ROLE_T.ENABLE_FLAG IS '是否有效。';

COMMENT ON COLUMN CMS_ROLE_T.ROLE_TYPE IS '角色类型，WORK_PLATFORM：工作平台；PUB_PLATFORM：发布平台，ADMIN_PLATFORM：管理平台。';

COMMENT ON COLUMN CMS_ROLE_T.COMP_CODE IS '出版社代码。';

COMMENT ON COLUMN CMS_ROLE_T.REMARKS IS '备注。';

COMMENT ON COLUMN CMS_ROLE_USER_REL_T.REL_ID IS '关系ID，主键。';

COMMENT ON COLUMN CMS_ROLE_USER_REL_T.ROLE_ID IS '角色ID。';

COMMENT ON COLUMN CMS_ROLE_USER_REL_T.USER_ID IS '用户ID。';

COMMENT ON COLUMN CMS_ROLLBACK_LOG_T.LOG_ID IS '回退日志ID，主键';

COMMENT ON COLUMN CMS_ROLLBACK_LOG_T.DOC_ID IS '关联的文档ID';

COMMENT ON COLUMN CMS_ROLLBACK_LOG_T.ROLLBACK_OPERATOR IS '操作人';

COMMENT ON COLUMN CMS_ROLLBACK_LOG_T.OPERATION_TIME IS '操作时间';

COMMENT ON COLUMN CMS_ROLLBACK_LOG_T.ROLLBACK_REASON IS '退回原因';

COMMENT ON COLUMN CMS_SERVER_CONFIG_T.CONFIG_ID IS '主键ID。';

COMMENT ON COLUMN CMS_SERVER_CONFIG_T.HOST IS '服务器域名/IP';

COMMENT ON COLUMN CMS_SERVER_CONFIG_T.PORT IS '端口号。';

COMMENT ON COLUMN CMS_SERVER_CONFIG_T.ADMIN_USERNAME IS '管理员用户名。';

COMMENT ON COLUMN CMS_SERVER_CONFIG_T.ADMIN_PASSWORD IS '管理员密码。';

COMMENT ON COLUMN CMS_SERVER_CONFIG_T.SERVER_TYPE IS '服务器类型。';

COMMENT ON COLUMN CMS_SERVER_CONFIG_T.ENABLE_FLAG IS '是否有效。';

COMMENT ON COLUMN CMS_SERVER_CONFIG_T.VERSION IS '版本号';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.TEACHING_PLAN_ID IS '教案ID，主键';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.DOC_ID IS '文档id';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.SOURCE_BOOK_DOC_ID IS '来源图书docId';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.SOURCE_BOOK_NAME IS '来源图书名';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.SOURCE_BOOK_ISBN IS '来源图书isbn';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.PUBLISHING_HOUSE IS '出版社';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.SOURCE_BOOK_TYPE IS '来源图书分类';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.COMP_CODE IS '所属部门';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.EDITOR IS '责任编辑';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.TEACHING_PLAN_NAME IS '教案名称';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.PRODUCER IS '制作者';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.TEACHING_PLAN_TYPE IS '教案类型';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.COPYRIGHT_FLAG IS '版权信息(有/无)';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.KEYWORD IS '关键词';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_TEACHING_PLAN_T.TEACHING_PLAN_STORE_TIME IS '入库时间';

COMMENT ON COLUMN CMS_THEME_T.THEME_NAME IS '主题名称';

COMMENT ON COLUMN CMS_THEME_T.THEME_DESC IS '主题描述';

COMMENT ON COLUMN CMS_THEME_T.BINDING_THEME_ID IS '绑定的应用主题ID';

COMMENT ON COLUMN CMS_THEME_T.BINDING_THEME_NAME IS '绑定的应用主题名称';

COMMENT ON COLUMN CMS_THEME_T.STATUS IS '状态';

COMMENT ON COLUMN CMS_THEME_T.COMP_CODE IS '出版社代码';

COMMENT ON COLUMN CMS_USER_T.USER_ID IS '用户ID，主键。';

COMMENT ON COLUMN CMS_USER_T.USER_NAME IS '登录名。';

COMMENT ON COLUMN CMS_USER_T.PASSWORD IS '密码。';

COMMENT ON COLUMN CMS_USER_T.DIPLAY_NAME IS '显示名，姓名。';

COMMENT ON COLUMN CMS_USER_T.COMP_CODE IS '出版社代码。';

COMMENT ON COLUMN CMS_USER_T.ENABLE_FLAG IS '是否有效。';

COMMENT ON COLUMN CMS_USER_T.REMARKS IS '备注。';

COMMENT ON COLUMN CMS_VIDEO_T.DOC_ID IS '文档ID';

COMMENT ON COLUMN CMS_VIDEO_T.FILE_NAME IS '文件名称';

COMMENT ON COLUMN CMS_VIDEO_T.FILE_FORMAT IS '文件格式';

COMMENT ON COLUMN CMS_VIDEO_T.FILE_SIZE IS '文件大小';

COMMENT ON COLUMN CMS_VIDEO_T.FILE_TIME IS '文件时长';

COMMENT ON COLUMN CMS_VIDEO_T.FILE_STORE_TIME IS '入库时间';

COMMENT ON COLUMN CMS_VIDEO_T.SERIES_NAME IS '系列名称';

COMMENT ON COLUMN CMS_VIDEO_T.ITEM_CODE IS '物料号';

COMMENT ON COLUMN CMS_VIDEO_T.VIDEO_TYPE IS '视频分类';

COMMENT ON COLUMN CMS_VIDEO_T.CARRIER_TYPE IS '载体类型';

COMMENT ON COLUMN CMS_VIDEO_T.LANG IS '语种';

COMMENT ON COLUMN CMS_VIDEO_T.EDITOR IS '责任编辑';

COMMENT ON COLUMN CMS_VIDEO_T.TEXT_EDITOR IS '文字编辑';

COMMENT ON COLUMN CMS_VIDEO_T.PRODUCER IS '制作人';

COMMENT ON COLUMN CMS_VIDEO_T.PUB_TIME IS '制作/出版时间';

COMMENT ON COLUMN CMS_VIDEO_T.ASSORT_BOOK IS '配套图书';

COMMENT ON COLUMN CMS_VIDEO_T.COMP_CODE IS '分社';

COMMENT ON COLUMN CMS_VIDEO_T.KEYWORD IS '关键词';

COMMENT ON COLUMN CMS_VIDEO_T.CONTENT_DESC IS '内容简介';

COMMENT ON COLUMN CMS_VIDEO_T.REMARKS IS '备注';

COMMENT ON COLUMN CMS_VIDEO_T.PREVIEW_URL IS '预览URL。';

COMMENT ON COLUMN CMS_VIDEO_T.SCRIPT IS '台本';

COMMENT ON COLUMN CMS_XC_INFO_T.XC_INFO_ID IS '宣传信息ID，主键';

COMMENT ON COLUMN CMS_XC_INFO_T.TITLE IS '标题';

COMMENT ON COLUMN CMS_XC_INFO_T.AUTHOR IS '作者';

COMMENT ON COLUMN CMS_XC_INFO_T.CONTENT IS '内容';

COMMENT ON COLUMN CMS_XC_INFO_T.TYPE IS '类型';

CREATE SEQUENCE CMS_3RD_AUTHORIZATION_ITEMS_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_3RD_AUTHORIZATION_ITEM_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_3RD_AUTHORIZATION_ORDER_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_ACTIVITY_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_ATTACH_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_AUDIO_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_AUTHOR_COPYRIGHT_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_BOOK_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_CATEGORY_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_CHAPTER_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_COMPANY_COPYRIGHT_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_COMP_LIB_REL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_COURSEWARE_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_DOCBOOK_JOB_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_DOCBOOK_MONITOR_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_DOC_CATEGORY_REL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_DOC_GROUP_REL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_DOC_REL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_DOC_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_DOC_UCM_REL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_ELEC_PROD_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_FIGURE_EXIF_INFO_S INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_FIGURE_GROUP_S INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_GATHER_MONITOR_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_ILLUSTRATION_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_JB_INFO_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_LIB_CATEGORY_G_REL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_LIB_RES_REL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_LOOKUP_TYPE_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_LOOKUP_VALUE_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_MATERIAL_FIGURE_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_NEWSPAPER_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_NEWSPAPER_SETUP_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_NEWS_SETUP_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_PERIODICAL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_PERIODICAL_SETUP_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_PERIOD_SETUP_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_PHOTOGRAPHY_FIGURE_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_PROCESS_LOG_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_RES_EXP_APPLY_H_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_RES_EXP_APPLY_L_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_RES_TEMPLATE_REL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_RES_TEMPLATE_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_RES_TEMP_SHELF_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_ROLE_LIB_REL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_ROLE_RES_REL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_ROLE_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_ROLE_USER_REL_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_ROLLBACK_LOG_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_TEACHING_PLAN_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_THEME_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_USER_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_VIDEO_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE CMS_XC_INFO_S INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1 CACHE 20;
