package com.zypg.cms.work.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 03 18:54:18 CST 2014
// ---------------------------------------------------------------------
public interface CommonAM extends ApplicationModule {
    void insertGatherMonitorRecord(oracle.jbo.domain.Number docId, String fileName, String filePath);
}
