package com.zypg.cms.work.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 07 15:44:59 CST 2014
// ---------------------------------------------------------------------
public interface MaterialFigureAM extends ApplicationModule {
    oracle.jbo.domain.Number preEditMaterial(String mode, oracle.jbo.domain.Number docId,String compCode);
}
